### ISSUE TITLE
dark btn is invisible when disabled 

### ISSUE THREAD

**Issue by FatehDzIt** [nuxt-community/vuetify-module#102]
**Module version**
1.2.0

**Describe the bug**
button with dark att is invisible when disabled 
`<v-btn color="blue" @click.prevent="create" :disabled="!valid" dark>Create</v-btn>`

![Untitled](https://user-images.githubusercontent.com/42697678/62528559-f2a1a200-b834-11e9-9a30-fb14884460d1.png)

**Comment by kevinmarrec** [comment]
@FatehDzIt See https://github.com/vuetifyjs/vuetify/issues/4482

> Dark shouldn't specifically be used to make text white. My rule of thumb is whatever color background the element is on. In this case you should opt to use class="white--text".

You can also use last comment workaround which is : `:dark="valid"`

**Comment by FatehDzIt** [comment]
i understand 
your  workaround also worked
thank you for your help
