### ISSUE TITLE
Got duplicate style#vuetify-theme-stylesheet

### ISSUE THREAD

**Issue by azulkipli** [nuxt-community/vuetify-module#103]
**Module version**
@nuxtjs/vuetify: ^1.0.0
create-nuxt-app v2.9.2

**Describe the bug**
When I generate new nuxt app and choose UI Framework : Vuetify
I got duplicate style#vuetify-theme-stylesheet tag which has same CSS content.

**To Reproduce**
Just generate new nuxt app with create-nuxt-app v2.9.2
`yarn create nuxt-app nuxt-vuetify-2.x`
Run `yarn dev`, inspect element check the style tag on head
I clone this https://codesandbox.io/s/nuxtjs-vuetify-v0k7i too then run on local, got same case.

**Expected behavior**
Include style#vuetify-theme-stylesheet only once
 
**Screenshots**
![Screen Shot 2019-08-06 at 18 36 49](https://user-images.githubusercontent.com/8231792/62537231-1f2bdd00-b87a-11e9-8f73-1468d6ea2da2.png)

**Additional context**
[package.json.txt](https://github.com/nuxt-community/vuetify-module/files/3471999/package.json.txt)
[nuxt.config.js.txt](https://github.com/nuxt-community/vuetify-module/files/3472004/nuxt.config.js.txt)

**Comment by kevinmarrec** [comment]
Hi @azulkipli , it's a known issue, it only happens with`spa` mode it's what causes #69.
I'm still working on a fix around Vuetify source code.

**Comment by azulkipli** [comment]
hmm, thanks @kevinmarrec I will follow related issue
