### ISSUE TITLE
Migrating to Vuetify 2

### ISSUE THREAD

**Issue by tsolrm** [nuxt-community/vuetify-module#107]
I am having a lot of issues migrating my nuxt app to vuetify 2. I have tried my best to follow the migration guide and I have encountered the following issues:
- Warnings about missing modules: vue-loader/file-loader. Haven't had these before.. Installed them.

Latest issue preventing build:
![image](https://user-images.githubusercontent.com/16368445/62677412-25b77300-b9a6-11e9-822d-b80e1f617b4b.png)

Can somebody give me hope that they have upgraded vuetify 1.5 to 2 in a nuxt app? Or should I abandon my attempts until the migration path is more stable.

**Comment by kevinmarrec** [comment]
@tsolrm Please provide a repository with the issue, I can't really help just with the error.

I should be able to quick fix it :)

**Comment by tsolrm** [comment]
I cannot post a link to a repo as it is a private one.. however I will post package.json and nuxt configs maybe you spot anything in those?

`const webpack = require('webpack')
const ImageminPlugin = require('imagemin-webpack-plugin').default
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')
const imageminMozjpeg = require('imagemin-mozjpeg')

module.exports = {
  mode: 'universal',

  /*
   ** Headers of the page
   */
  head: {
    title: '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content:
          ''
      }
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }]
  },

  /*
   ** Customize the progress-bar color
   */
  loading: { color: '#fff' },

  /*
   ** Plugins to load before mounting the App
   */
  plugins: [
    '@/plugins/setup',
    '@/plugins/vuetify',
    '@/plugins/autoregister',
    '@/plugins/feedback',
    '@/plugins/breakpoint',
    '@/plugins/navigation',
    '@/plugins/page-links'
  ],

  /*
   ** Nuxt.js modules
   */
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/sitemap',
    'nuxt-webfontloader'
  ],

  devModules: ['@nuxtjs/vuetify'],

  sitemap: {
    hostname: '',
    gzip: true,
    routes: []
  },

  /*
   ** Axios module configuration
   */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
  },

  webfontloader: {
    google: {
      families: ['Karla:300,400,500,700|Material+Icons']
    }
  },

  /*
   ** Build configuration
   */
  build: {
    babel: {
      plugins: ['@babel/plugin-proposal-optional-chaining']
    },
    transpile: ['vuetify/lib'],
    plugins: [new VuetifyLoaderPlugin()],
    extractCSS: true,

    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      if (ctx.isClient && ctx.isDev) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })

        config.devtool = 'source-map'
      }

      if (!ctx.isDev) {
        config.plugins.push(
          new ImageminPlugin({
            plugins: [
              imageminMozjpeg({
                quality: 90,
                progressive: true
              })
            ]
          })
        )
      }

      config.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/))
    }
  }
}
`


and 

`{
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon -r dotenv/config server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node -r dotenv/config server/index.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "prettier": "prettier --check **/*.{js,vue} --ignore-path .gitignore",
    "precommit": "yarn lint && yarn prettier",
    "release": "yarn lint && yarn prettier && release-it --no-npm.publish"
  },
  "repository": {
    "type": "git",
    "url": "git@gitlab.com:bluelilo/frontend/frontend.git"
  },
  "dependencies": {
    "@bazzite/nuxt-optimized-images": "0.2.1",
    "@bluelilo/node-core": "1.0.1",
    "@nuxtjs/axios": "5.5.4",
    "@nuxtjs/pwa": "2.6.0",
    "@nuxtjs/sitemap": "1.2.0",
    "apollo-cache-inmemory": "1.6.2",
    "apollo-client": "2.6.3",
    "apollo-link-http": "1.5.15",
    "dotenv": "8.0.0",
    "express": "4.17.1",
    "express-prometheus-middleware": "0.6.1",
    "graphql": "14.4.2",
    "graphql-tag": "2.10.1",
    "imagemin-mozjpeg": "8.0.0",
    "imagemin-webpack-plugin": "2.4.2",
    "isomorphic-fetch": "2.2.1",
    "moment": "2.24.0",
    "nuxt": "2.8.1",
    "nuxt-env": "0.1.0",
    "nuxt-merge-asyncdata": "0.1.1",
    "nuxt-webfontloader": "1.1.0",
    "vue": "2.6.10",
    "vue-apollo": "3.0.0-beta.29",
    "vuetify": "1.5.16"
  },
  "devDependencies": {
    "@babel/core": "7.5.4",
    "@babel/plugin-proposal-optional-chaining": "7.2.0",
    "@nuxtjs/eslint-config": "1.0.1",
    "@nuxtjs/vuetify": "^1.2.1",
    "babel-eslint": "10.0.2",
    "cross-env": "5.2.0",
    "eslint": "5.16.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-config-standard": "12.0.0",
    "eslint-loader": "2.2.1",
    "eslint-plugin-import": "2.18.0",
    "eslint-plugin-jest": "22.7.2",
    "eslint-plugin-node": "9.1.0",
    "eslint-plugin-nuxt": "0.4.3",
    "eslint-plugin-prettier": "3.1.0",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-standard": "4.0.0",
    "eslint-plugin-vue": "5.2.3",
    "file-loader": "^4.2.0",
    "nodemon": "1.19.1",
    "prettier": "1.18.2",
    "release-it": "12.3.3",
    "vue-loader": "^15.7.1",
    "vue-template-compiler": "2.6.10",
    "webpack": "4.35.3",
    "webpack-bundle-analyzer": "3.3.2"
  }
}
`

**Comment by tsolrm** [comment]
I cannot post a link to a repo as it is a private one.. however I will post package.json and nuxt configs maybe you spot anything in those?

```const webpack = require('webpack')
const ImageminPlugin = require('imagemin-webpack-plugin').default
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')
const imageminMozjpeg = require('imagemin-mozjpeg')

module.exports = {
  mode: 'universal',

  /*
   ** Headers of the page
   */
  head: {
    title: '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content:
          ''
      }
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }]
  },

  /*
   ** Customize the progress-bar color
   */
  loading: { color: '#fff' },

  /*
   ** Plugins to load before mounting the App
   */
  plugins: [
    '@/plugins/setup',
    '@/plugins/vuetify',
    '@/plugins/autoregister',
    '@/plugins/feedback',
    '@/plugins/breakpoint',
    '@/plugins/navigation',
    '@/plugins/page-links'
  ],

  /*
   ** Nuxt.js modules
   */
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/sitemap',
    'nuxt-webfontloader'
  ],

  devModules: ['@nuxtjs/vuetify'],

  sitemap: {
    hostname: '',
    gzip: true,
    routes: []
  },

  /*
   ** Axios module configuration
   */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
  },

  webfontloader: {
    google: {
      families: ['Karla:300,400,500,700|Material+Icons']
    }
  },

  /*
   ** Build configuration
   */
  build: {
    babel: {
      plugins: ['@babel/plugin-proposal-optional-chaining']
    },
    transpile: ['vuetify/lib'],
    plugins: [new VuetifyLoaderPlugin()],
    extractCSS: true,

    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      if (ctx.isClient && ctx.isDev) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })

        config.devtool = 'source-map'
      }

      if (!ctx.isDev) {
        config.plugins.push(
          new ImageminPlugin({
            plugins: [
              imageminMozjpeg({
                quality: 90,
                progressive: true
              })
            ]
          })
        )
      }

      config.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/))
    }
  }
}
```


and 

```{
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon -r dotenv/config server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node -r dotenv/config server/index.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "prettier": "prettier --check **/*.{js,vue} --ignore-path .gitignore",
    "precommit": "yarn lint && yarn prettier",
    "release": "yarn lint && yarn prettier && release-it --no-npm.publish"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "dependencies": {
    "@bazzite/nuxt-optimized-images": "0.2.1",
    "@bluelilo/node-core": "1.0.1",
    "@nuxtjs/axios": "5.5.4",
    "@nuxtjs/pwa": "2.6.0",
    "@nuxtjs/sitemap": "1.2.0",
    "apollo-cache-inmemory": "1.6.2",
    "apollo-client": "2.6.3",
    "apollo-link-http": "1.5.15",
    "dotenv": "8.0.0",
    "express": "4.17.1",
    "express-prometheus-middleware": "0.6.1",
    "graphql": "14.4.2",
    "graphql-tag": "2.10.1",
    "imagemin-mozjpeg": "8.0.0",
    "imagemin-webpack-plugin": "2.4.2",
    "isomorphic-fetch": "2.2.1",
    "moment": "2.24.0",
    "nuxt": "2.8.1",
    "nuxt-env": "0.1.0",
    "nuxt-merge-asyncdata": "0.1.1",
    "nuxt-webfontloader": "1.1.0",
    "vue": "2.6.10",
    "vue-apollo": "3.0.0-beta.29",
    "vuetify": "1.5.16"
  },
  "devDependencies": {
    "@babel/core": "7.5.4",
    "@babel/plugin-proposal-optional-chaining": "7.2.0",
    "@nuxtjs/eslint-config": "1.0.1",
    "@nuxtjs/vuetify": "^1.2.1",
    "babel-eslint": "10.0.2",
    "cross-env": "5.2.0",
    "eslint": "5.16.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-config-standard": "12.0.0",
    "eslint-loader": "2.2.1",
    "eslint-plugin-import": "2.18.0",
    "eslint-plugin-jest": "22.7.2",
    "eslint-plugin-node": "9.1.0",
    "eslint-plugin-nuxt": "0.4.3",
    "eslint-plugin-prettier": "3.1.0",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-standard": "4.0.0",
    "eslint-plugin-vue": "5.2.3",
    "file-loader": "^4.2.0",
    "nodemon": "1.19.1",
    "prettier": "1.18.2",
    "release-it": "12.3.3",
    "vue-loader": "^15.7.1",
    "vue-template-compiler": "2.6.10",
    "webpack": "4.35.3",
    "webpack-bundle-analyzer": "3.3.2"
  }
}
```

**Comment by kevinmarrec** [comment]
1. Remove 
```js
transpile: ['vuetify/lib'],
plugins: [new VuetifyLoaderPlugin()],
``` 
from `build.options`

2. Remove `vuetify@1.5.16` from your dependencies.

Also please read if you didn't yet : https://github.com/nuxt-community/vuetify-module/blob/master/MIGRATION_GUIDE.md

**Comment by kevinmarrec** [comment]
Also remove

```
'@/plugins/vuetify',
``` from plugins

I won't be able to help further without repository, you seemed to have too much customization of Vuetify installation before upgrade (you seemed to not use Nuxt module)

**Comment by tsolrm** [comment]
I did not previously use @nuxt/vuetify module however whatever setup I had - came out of the box with nuxt. I have not made any changes to the config manually apart from extending the styles and adding vuetify plugin file which overrides breakpoints. I will try your suggestions now, thank you

**Comment by tsolrm** [comment]
@kevinmarrec thank you for your comments. Whilst they didn't resolve my problem - they did help me understand it a bit more. It does look like I had some sort of customized build set up before although I am not sure why as I used the universal mode of the create-nuxt-app.

I have resolved my build issues by installing a clean nuxt app alongside and comparing my nuxt-config/package.json to it and purging anything that didn't look like it was required. After this process I ended up with a building solution. Now I just have to deal with the devastation of the breaking changes of Vuetify lol..

I do have 1 last question, I get these 2 warnings when running a yarn install, whilst they don't affect the build process - perhaps you could explain them please?

![image](https://user-images.githubusercontent.com/16368445/62711026-486e7980-b9f0-11e9-8b2f-c00aa424d777.png)

**Comment by kevinmarrec** [comment]
@tsolrm Alright cool if you suceed to end up with a building solution :) Yeah, you need to get through all the [https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide](Vuetify Upgrade guide).

About the 2 warnings, nothing to worry about, `vue` & `vue-template-compiler` are shipped by `nuxt`.
It's just `yarn` not being smart enough to detect it, I guess.
