### ISSUE TITLE
Manual import of components

### ISSUE THREAD

**Issue by Yihao-G** [nuxt-community/vuetify-module#109]
I'm trying to add [vuetify-toast-snackbar](https://github.com/eolant/vuetify-toast-snackbar) library in, which requires [manually importing](https://github.com/eolant/vuetify-toast-snackbar#vue-loader-eg-nuxtjs). Is there a way to do [manually importing](https://vuetifyjs.com/en/customization/a-la-carte#manually-importing) without importing them in .vue files? 

Thank you

**Comment by kevinmarrec** [comment]
Hi @Yihao-G,

I did some tests, and for now it's not possible, cause manual import of components need to be registered around `Vue.use(Vuetify, components : {})`, and this is what our code looks like : https://github.com/nuxt-community/vuetify-module/blob/master/lib/templates/plugin.js#L5.

So it's more likely a feature request I'll be pleased to dive in soon :)
Thanks for pointing this missing feature out !

PS : There is no workaround AFAIK, unless not using this module and do custom Vuettify plugin.
