### ISSUE TITLE
Difficulties overriding SCSS variables

### ISSUE THREAD

**Issue by tsolrm** [nuxt-community/vuetify-module#111]
Before migrating to vuetify 2, I was able to override the css breakpoints as I wished via a stylus file. I am attempting to do the same here, please see the 2 screenshots below.

![image](https://user-images.githubusercontent.com/16368445/62817378-71e0ef80-bb2d-11e9-8781-a194e5e78c70.png)
![image](https://user-images.githubusercontent.com/16368445/62817384-83c29280-bb2d-11e9-9da9-28dad08521e1.png)

This works for **grids only**. This does not work for display helpers, so for example _hidden-xs-only_

To get those to work I am having to do this:
![image](https://user-images.githubusercontent.com/16368445/62817396-c5ebd400-bb2d-11e9-8949-399e4e57059b.png)

Is there a way to set up the breakpoints so that they affect everything as they did before?

**Comment by kevinmarrec** [comment]
@tsolrm It's probably something you could ask on Vueitfy discord (#release-migration channel). Cause I don't think I've any clues for now and that this is directly related to Vuetify 2 migration and bot the Nuxt module itself 😄

**Comment by iamareebjamal** [comment]
Define grid breakpoints before importing

https://github.com/vuetifyjs/vuetify/issues/8134

**Comment by kevinmarrec** [comment]
Thanks for the link @iamareebjamal 
@tsolrm Following my last comment and that it seems to be a documentation lack around Vuetify itself, I'm closing this here.

Please follow https://github.com/vuetifyjs/vuetify/issues/8134 thread and/or Vuetify discord for further help.
