### ISSUE TITLE
Dark theme always active after removing the dark prop from v-app component

### ISSUE THREAD

**Issue by begueradj** [nuxt-community/vuetify-module#114]
**Module version**
"@nuxtjs/vuetify": "^1.0.0",

**Describe the bug**
When I remove dark prop from v-app component, the dark theme is still active even when re-launch the server after clearing the cache.

**Steps to reproduce the behavior**:

1.  Run yarn `create nuxt-app my-app`
2.  In `layouts/default.vue` remove **dark** prop from `v-app` component

**Expected behavior**
When I remove **dark** prop from `v-app` component, I must see the webpage light

Billal Begueradj

**Comment by kevinmarrec** [comment]
@begueradj No cause you probably still have `dark: true` in your `nuxt.config.js`, you need it to remove it if you want light theme by default.

https://github.com/nuxt/create-nuxt-app/blob/master/template/nuxt/nuxt.config.js#L135

**Comment by begueradj** [comment]
You are right, I forgot that since several months ago, Vuetify settings were moved from the plugins folder to nuxt.config.js file. Thank you very much

**Comment by riux** [comment]
Yes, but if I want to have dark and light in different layouts

**Comment by timitalia** [comment]
The theme attribute (eg. 'dark' or 'light') gets ignored in the <v-app> element.
