### ISSUE TITLE
Is it possible to use a stable version of Nuxt with this module?

### ISSUE THREAD

**Issue by douira** [nuxt-community/vuetify-module#117]
Can I use the regular stable version of nuxt with this module? If so, how do I configure it to do that? I'm umcomfortable using this module in production if it requires the nuxt-edge version which might be unstable.

**Comment by kevinmarrec** [comment]
@douira It doesn't use `nuxt-edge`, it is only used as development dependency for our tests :)

**Comment by kevinmarrec** [comment]
It's a module so it will use whatever you have installed, `nuxt` or `nuxt-edge`.

**Comment by douira** [comment]
ok thanks for the info.
