### ISSUE TITLE
Where is the option to use mdi SVG icons?

### ISSUE THREAD

**Issue by douira** [nuxt-community/vuetify-module#121]
The documentation of this module says using only a few icons through the SVG package is better than using the whole iconfont. How do I specify that I only want to use a few icons and how do I tell this module to use the mdi SVGs?

**Comment by kevinmarrec** [comment]
@douira It's specificied in Vuetify docs :
https://vuetifyjs.com/en/customization/icons#install-material-design-icons-js-svg

**Comment by paulvonber** [comment]
@kevinmarrec it is specified, but doesn't react to any changes and still loading font from cdn

**Comment by kevinmarrec** [comment]
@paulvonber 
Check https://github.com/nuxt-community/vuetify-module#defaultassets, you need to disable `defaultAssets.icons` to prevent loading default icon font from CDN.

**Comment by kirillgroshkov** [comment]
Yes. You need to disable `defaultAssets` in `nuxt.config.js` `vuetify`.

Then load the icon manually like this:

```vue
<template>
      <v-btn>
        <v-icon>{{ mdiChevronLeft }}</v-icon>
      </v-btn>
</template>

<script>
import { mdiChevronLeft } from '@mdi/js'

@Component
export default class extends Vue {
  readonly mdiChevronLeft = mdiChevronLeft
}
</script>

```
