### ISSUE TITLE
vuetify a la carte does not load the style of components completely

### ISSUE THREAD

**Issue by DThink** [nuxt-community/vuetify-module#13]
hello, im trying to generate a static universal app with nuxt-ts + vuetify. The plugin works fine until I dont activate the treeShake mode with css disabled.
I do not receive any error but the style of the page is not completely loaded.

after i run the command `yarn run generate`

this is the result with css enabled (final bundle 2.2mb)

```
  modules: [
    '@nuxtjs/vuetify'
  ],
  vuetify: {
    materialIcons: true,
    css: true,
    treeShake: true
  }
```
![Screenshot from 2019-03-14 23-44-19](https://user-images.githubusercontent.com/18085313/54396750-5247b700-46b4-11e9-8e46-76566a47a992.png)

this is the result with css disabled and treeshake enabled (final bundle 900kb)

```
  modules: [
    '@nuxtjs/vuetify'
  ],
  vuetify: {
    materialIcons: true,
    css: false,
    treeShake: true
  }
```

![Screenshot from 2019-03-14 23-42-26](https://user-images.githubusercontent.com/18085313/54396781-6f7c8580-46b4-11e9-817c-5ac8f5424337.png)

The style of the components appear to be partially loaded.

my package.json file is this

```
{
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "nuxt-ts build",
    "lint": "tslint --project .",
    "dev": "nuxt-ts",
    "generate": "nuxt-ts generate",
    "post-update": "yarn upgrade --latest",
    "start": "nuxt-ts start"
  },
  "dependencies": {
    "@nuxt/config-edge": "^2.5.0-25874561.ff93d14b",
    "@nuxtjs/vuetify": "^0.5.5",
    "axios": "^0.18.0",
    "loader": "^2.1.1",
    "nuxt-ts": "latest",
    "tachyons": "^4.11.1",
    "vue-property-decorator": "^7.3.0",
    "vuex-class": "^0.3.1"
  },
  "devDependencies": {
    "style-loader": "^0.23.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "tslint-config-standard": "^8.0.1",
    "vue-cli-plugin-vuetify": "^0.5.0",
    "vuetify-loader": "^1.2.1"
  }
}
```

**Comment by kevinmarrec** [comment]
@DThink Even if you're using ALaCarte, you need to use `vuetify/src/stylus/app.styl` which contains global styles. Did you add it to `css` array of your configuration ?

https://vuetifyjs.com/en/framework/a-la-carte#required-styles

**Comment by ricardogobbosouza** [comment]
@kevinmarrec can closed?

**Comment by kevinmarrec** [comment]
Solution & link should have correctly answered, and no answers from opener, so closing it.
