### ISSUE TITLE
Change font-family is not working

### ISSUE THREAD

**Issue by GeoAbbey** [nuxt-community/vuetify-module#136]
**Module version**
1.5.0

**Describe the bug**
The default font-family is Roboto which I need to change to Montserrat to conform to my design. However, I have tried to change the font-family in the variable.scss file with `$body-font-family: 'Montserrat', sans-serif`, but not working.

**Expected behavior**
The font-family supposed to change to the set font-family (Montserrat in my case) in the variable.scss

**Comment by kevinmarrec** [comment]
@GeoAbbey Could you please provide a repository with the bug ?

Also did you :
1) set `defaultAssets.font` to `false` ?
2) add "Montserrat" font to your project (using `head` config options, `nuxt-webfontloader`) ?

**Comment by GeoAbbey** [comment]
https://codesandbox.io/s/font-test-284p1

The above is the link to the sandbox that reproduces the issue.

@kevinmarrec Yes, I did set `defaultAssets.font` to `false` and added "Montserrat" font via `nuxt-webfontloader`

**Comment by kevinmarrec** [comment]
@GeoAbbey Two things I noticed :
1) You're not registering `nxut-webfontloader` module, only setuping his options.
2) [https://github.com/nuxt-community/vuetify-module#customvariables](customVariables) only works with `treeShake: true` (it's mentionned in this module documentation)

**Comment by GeoAbbey** [comment]
@kevinmarrec I forgot to add `nuxt-webfontloader` to the sandbox, but even when I finally added it, it didn't still work. I also activated `treeShake` in the vuetify configuration of the `nuxt.config.js`.

My configuration in the `nuxt.config.js` is as follows:

```
modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    'nuxt-webfontloader'
  ],

  webfontloader: {
    google: {
      families: ['Montserrat:400,500,700,900'] //Loads Lato font with weights 400 and 700
    }
  },

  vuetify: {
    customVariables: ['~/assets/variables.scss'],
    defaultAssets: {
      font: false
    },
    treeShake: true,
    theme: {
      themes: {
        light: {
          primary: '#0415ca',
          accent: '#6D6D6D',
          secondary: '#06d79c',
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        }
      }
    }
  },
```

Please, is there anything else I'm not doing?

**Comment by kevinmarrec** [comment]
@GeoAbbey Can you create a GitHub repostiory with the configuration you have `treeShake: true` ?
I can't fork a GitHub repo from CodeSandbox (it will only create a new sandbox).

**Comment by GeoAbbey** [comment]
Alright. On it.

**Comment by GeoAbbey** [comment]
@kevinmarrec Here is the link to the GitHub repository:

https://github.com/GeoAbbey/font-test

**Comment by kevinmarrec** [comment]
@GeoAbbey I investigated and in
https://github.com/GeoAbbey/font-test/blob/master/assets/variables.scss

You need to set `$body-font-family` before the import.
Furthermore, the `import` is needed only if you need to use variables from Vuetify like palette colors.

**Comment by kevinmarrec** [comment]
Please confirm it works, I'll add notes in documentation about font-family change.

**Comment by GeoAbbey** [comment]
@kevinmarrec It works perfectly. 
Thanks a million.
