### ISSUE TITLE
Vuetify options are loaded on client

### ISSUE THREAD

**Issue by amritk** [nuxt-community/vuetify-module#140]
**Module version**
1.6.0

**Describe the bug**
I tried switching over to the nuxt vuetify module after this issue: https://github.com/nuxt-community/vuetify-module/issues/133#issuecomment-525611260 but I noticed that when loading vuetify.options.js it is being hit in the client. The reason I do not want this is I am using vuetify-loader to load my own components. When using vuetify directly as a nuxt plugin, these options are only hit when you initially build. When using the nuxt vuetify module they seem to be hit on refresh? (maybe just showing me the error in the client every time)

**To Reproduce**
https://github.com/amritk/nuxt-vuetify-issue

**Steps to reproduce the behavior:**
yarn dev
You will see the error on the client in developer tools
```typescript
Uncaught TypeError: fs.readdir is not a function
    at readdir (webpack-internal:///./node_modules/recursive-readdir/index.js:42)
    at eval (webpack-internal:///./src/plugins/vuetify.ts:18)
    at Object../src/plugins/vuetify.ts (app.js:2000)
    at __webpack_require__ (runtime.js:786)
    at fn (runtime.js:151)
    at eval (webpack-internal:///./.nuxt/index.js:54)
    at Object../.nuxt/index.js (app.js:191)
    at __webpack_require__ (runtime.js:786)
    at fn (runtime.js:151)
    at Object.eval (webpack-internal:///./.nuxt/client.js:19)
```

**Expected behavior**
I only expect these options to be hit on the server when you build the first time, there is no need for them to be hit on the client.

**Additional context**
I am trying to use the nuxt vuetify module and I believe this is the last issue holding me back.

**Comment by kevinmarrec** [comment]
@amritk 

It isn't documented yet but `loaderOptions` is around `treeShake` option.
And `treeShake.loaderOptions` isn't a framework option (i.e. not to be used in `vuetify.options.js`).

`treeShake.loaderOptions` should be set in **module** options (https://github.com/amritk/nuxt-vuetify-issue/blob/master/nuxt.config.js#L43)

```js
vuetify: { // Module options
  treeShake: {
    loaderOptions: {
      // vuetify-loader options (match function)
    }
  }
  optionsPath: './vuetify.options.js' // Framework options
},
```
Module options are hit only once on the server.
Framework options are indeed hit at each refresh.

**Comment by amritk** [comment]
@kevinmarrec awesome thanks! Giving it another go in production now
