### ISSUE TITLE
How to preload vuetify theme

### ISSUE THREAD

**Issue by jackie-park** [nuxt-community/vuetify-module#148]
**Is your feature request related to a problem? Please describe.**
I don't know how to preload vuetify theme css.
I tried shouldPreload method but it doesn't seems working 
```
// nuxt.config.ts
render: {
    bundleRenderer: {
      shouldPreload: (file, type) => {
        return ['script', 'style', 'font'].includes(type)
      },
    },
  },
// vuetify option
theme: {
    options: {
      customProperties: true,
      minifyTheme: (css) => {
        return css.replace(/[\r\n|\r|\n]/g, '')
      },
    },
    dark: true,
    themes: {
      light: {
        primary: colors.grey.darken4,
        secondary: colors.amber.darken3,
        accent: colors.lightBlue.darken1,
        info: colors.blue.darken4,
        warning: colors.orange.darken4,
        error: colors.red.darken4,
        success: colors.green.darken3,
      },
      dark: {
        primary: colors.blue.darken2,
        secondary: colors.amber.darken3,
        accent: colors.grey.darken3,
        info: colors.teal.lighten1,
        warning: colors.amber.base,
        error: colors.deepOrange.accent4,
        success: colors.green.accent3,
      },
    },
  },
```
```
<link href="/_nuxt/28525bf520ad9181cd06.css" rel="stylesheet">
```
**Describe the solution you'd like**
```
<link rel="preload" href="/_nuxt/28525bf520ad9181cd06.css" as="style">
```

**Comment by kevinmarrec** [comment]
@jackie-park Not sure what you're going to achieve, I think you shouldn't have to `preload` it, it seems to be related to https://github.com/nuxt-community/vuetify-module/issues/143, components in Nuxt pages aren't preloaded with SSR but should be, if i'm right.

**Comment by kevinmarrec** [comment]
Any news @jackie-park ?

**Comment by kevinmarrec** [comment]
@jackie-park Vuetify theme css seems to be already preloaded when using SSR

**Comment by jackie-park** [comment]
![image](https://user-images.githubusercontent.com/38970917/64585330-4de62780-d3d3-11e9-9b32-36898e4e8d89.png)
![image](https://user-images.githubusercontent.com/38970917/64585347-60f8f780-d3d3-11e9-81b9-fbc465b22128.png)

**Comment by jackie-park** [comment]
I don't know how to preload this. Thanks.

**Comment by kevinmarrec** [comment]
Are you using SSR/SPA ? Static generation ?

**Comment by jackie-park** [comment]
I am using SPA.

**Comment by kevinmarrec** [comment]
I just think this file can't be preloaded, it is added at runtime by Nuxt when loading the page components.

**Comment by filipwronski** [comment]
I have the same issue. 
![image](https://user-images.githubusercontent.com/16827580/65328738-4f73d480-dbb7-11e9-9714-7777e302a189.png)

**Comment by kevinmarrec** [comment]
I think it's cause `vuetify-loader` doesn't lazy load components.
WIth #154 manual mode, people will be able to manually import Vuetify components everywhere and lazy load them. Which means that if there's still issue about `preload`, it's a Nuxt issue and not Vuetify module one.

**Comment by mseele** [comment]
@jackie-park did you find any solution for this? i'm using `nuxt generate` and run into the same problem.

**Comment by FandangoInPetto** [comment]
Same issue for me, this greatly impacts things like PageSpeed scores.

**Comment by bengineer19** [comment]
@kevinmarrec Did you come across a solution? 
This is really impacting lighthouse audits
![image](https://user-images.githubusercontent.com/6606828/78451362-214e7180-767d-11ea-9752-b2090a0ff57a.png)

**Comment by bengineer19** [comment]
Additionally in the request chaining section as well
![image](https://user-images.githubusercontent.com/6606828/78476318-4f46bb00-773c-11ea-8c76-6f1cd8c69283.png)

**Comment by jackie-park** [comment]
No solutions for this but I did some work for performance.
MinifyTheme, Preconnect, Flattening static folders, webfontloader, display swap for text, display block for icon and so on

**Comment by tincho425** [comment]
Same problem here, LightHouse tells there're 7.34s estimated savings 😲 All .css vuetify files.

**Comment by dylan-moore** [comment]
Me too. This is seriously hurting my LightHouse score.

**Comment by HoangKimDuc** [comment]
+1

**Comment by giancarllorojas** [comment]
I'm experiencing the same issue, anyone got some workaround?

**Comment by ujjwalagrawal17** [comment]
Facing same issue. Looking for a solution for this.

**Comment by turtlepile** [comment]
facing the same issue, any solution?
