### ISSUE TITLE
Error start app sample

### ISSUE THREAD

**Issue by berenicestr** [nuxt-community/vuetify-module#151]
Hi, 

There is something wrong with the libraries. I Download the demo https://codesandbox.io/s/nuxtjs-vuetify-v0k7i and when I try to do:

npm install --> its Ok!

npm run dev --> appears this error! 

<img width="1384" alt="Screenshot 2019-09-06 at 12 32 45" src="https://user-images.githubusercontent.com/15228105/64421879-f11d0100-d0a2-11e9-8164-9545aac13e15.png">

I try to replicate with a local project. When I clean the npm_modules and .nuxt folders I have the same error.

Any help?

Regards

**Module version**
The version of the module you're using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kevinmarrec** [comment]
Please upgrade Nuxt, last Vuetify version needs last vue-meta version. (2.x) that is shipped since Nuxt 2.9.

**Comment by berenicestr** [comment]
Thanks @kevinmarrec now its OK!
