### ISSUE TITLE
Example Lang with Nuxt - Vuetify module

### ISSUE THREAD

**Issue by berenicestr** [nuxt-community/vuetify-module#152]
Hi!

I am using Nuxt with internationalization nuxt-i18n  with this nuxt-vuetify module.

I would like to integrate Nuxt-i18n with Vuetify Internazionalization but I don't know if there is any option that I can configure or how can I do it.

I open a question here https://cmty.app/nuxt/nuxt-i18n/issues/c298 but I don't know how to resolve it.

I does apply the default lang, but when I switch other lang in Nuxt-i18n doesn't change the Lang of the Vuetify components.

I see there is an option in the Nuxt-vuetify module  to add in the nuxt-config.js with Lang in the Vuetify section properties.

Please, any documentation or example about it?

Thanks and Regards

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kevinmarrec** [comment]
@berenicestr 

https://github.com/nuxt-community/vuetify-module#optionspath

```js
// vuetify.options.js
export default function ({ app }) {
  return {
    lang: {
      t: (key, ...params) => app.i18n.t(key, params)
    }
  }
}
```

https://vuetifyjs.com/en/customization/internationalization

You would prefer a i18n section in docs that showcases how to switch `i18n` Vuetify locale when changing the global `i18n` one, right ?

**Comment by kevinmarrec** [comment]
Closing in favor of https://github.com/nuxt-community/vuetify-module/issues/153

**Comment by kevinmarrec** [comment]
@berenicestr Maybe you wanted to do :

```
Vue.mixin({
  watch: {
    '$i18n.locale' (newLocale) {
      this.$vuetify.lang.current = newLocale
    }
  }
})
``` as global mixin, or just add the `watch` in one of your layout/page depending on what you're willing to achieve.

**Comment by berenicestr** [comment]
Great! 🎉Its resolve my problem!🥳 Thank you very much @kevinmarrec 👏

My hero 🤩

**Comment by kamerat** [comment]
You can also create a plugin taking advantage of [beforeLanguageSwitch ](https://i18n.nuxtjs.org/callbacks#beforelanguageswitcholdlocale-newlocale)

This feels to me like a more clean nuxt way than a global watcher.

```js
// plugins/i18n.js
export default ({ app }) => {
    app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
        app.vuetify.framework.lang.current = newLocale;
    };
};
```

```js
// nuxt.config.js
// ...
plugins: ['~/plugins/i18n.js'],
// ...
```

**Comment by ajobi** [comment]
Updated plugin approach:

```
// plugins/i18n.js
export default ({ app }) => {
  app.vuetify.framework.lang.current = app.i18n.localeProperties.code

  app.i18n.onBeforeLanguageSwitch = (oldLocale, newLocale) => {
    app.vuetify.framework.lang.current = newLocale
  }
}
```

**Comment by arikw** [comment]
Adding my own two cents:

```js
// nuxt.config.js
export default {
  // ...
  i18n: {
    // ...
    onBeforeLanguageSwitch: (oldLocale, newLocale, isInitialSetup, context) => {
      const locale = context.i18n.locales.find(l => l.iso === newLocale) || {};
      const isRTL = locale.dir === 'rtl';
      if (isInitialSetup) {
        context.app.vuetify.preset.rtl = isRTL; // <--- makes vuetify direction work on initial page load
      }
      context.app.vuetify.framework.lang.current = locale.langCode;
      context.app.vuetify.framework.rtl = isRTL;
    }
  },
  vuetify: {
    // ...
    optionsPath: '~/config/vuetify.options.js'
  }
}
```

```js
// vuetify.options.js
export default function ({ app }) {
  return {
    lang: {
      t: (key, ...params) => app.i18n.t(key, params)
    }
  }
}
```
