### ISSUE TITLE
Build mode

### ISSUE THREAD

**Issue by kevinmarrec** [nuxt-community/vuetify-module#154]
**Is your feature request related to a problem? Please describe.**
We're currently not being able to use something else than (`dist/vuetify.js` + `dist/vuetify.css`) or `vuetify-loader`

**Describe the solution you'd like**
Be able to specify the **"build"** mode, including the following options :
- **full**
  - full Vuetify pre-build files
- **treeShake**
  - tree-shaking with `vuetify-loader`
- **manual**
  - Does nothing, user will need to manually import Vuetify components in the whole project
- **auto (Current behavior)**
  - Fallback to **full** mode in `development`(**nuxt dev**) for faster development 
  - Fallback to **treeShake** in `production`(**nuxt build**)

**Info**: Mode names are susceptible to change

Related issues that should be resolvable with this feature (not using `vuetify-loader` but manually importing components for more granular control)
https://github.com/nuxt-community/vuetify-module/issues/169
https://github.com/nuxt-community/vuetify-module/issues/143
https://github.com/nuxt-community/vuetify-module/issues/148

**Comment by MrJmpl3** [comment]
You need add a warning in the auto mode, because full mode and treeShake mode can be different CSS order.

**Comment by kevinmarrec** [comment]
@MrJmpl3 I'm not sure to understand, **auto** is already current behavior (last module version), why add a warning ?

**Comment by MrJmpl3** [comment]
Related: https://github.com/vuetifyjs/vuetify/issues/7933

In the full mode, import css and js pre builded , the order of css is correct.

But in tree-shake is if you are not cautious with imports the order of css broken the app

**Comment by kevinmarrec** [comment]
@MrJmpl3 Is the bug of CSS order still reproducible ? I would be interested trying to figure out what's going on

**Comment by MrJmpl3** [comment]
The issue was closed because the solution is be cautious with imports.

For example..
```js
import Toolbar from '@/components/organisms/Toolbar.vue';
import Footer from '@/components/organisms/Footer.vue';
```
The styles of Toolbar is loaded first and second the Footer

OR

```js
import Footer from '@/components/organisms/Footer.vue';
import Toolbar from '@/components/organisms/Toolbar.vue';
```
The styles of Footer is loaded first and second the Toolbar

The Vuetify team say: "We don't specify any order, it's dependant on the build configuration." in order words, depends of the order of the imports

**Comment by kevinmarrec** [comment]
@MrJmpl3 They are right, I mean it's user problem if his CSS can go crazy with its own customizations.
If you're talking about custom matching of Vuetify loader options, this is not something we're responsive of if CSS order matters cause your components do some CSS weird things.

That probably what they meant cause Vuetify components imports don't need specific order to work, so it's only user problem if his CSS is not correctly written.

**Comment by MrJmpl3** [comment]
For some reason , i recommend add a warning, because , in dev mode you project can be all correct, because the order of the imports don't import , but in production mode, the project will broken because the order of the imports start work.

**Comment by KaelWD** [comment]
Auto would also mean wider browser support in dev than in prod if babel isn't configured properly, and sass variables can't be changed with the full build.

**Comment by kevinmarrec** [comment]
@KaelWD treeShaking should better always be on by default then right ?

**Comment by MrJmpl3** [comment]
In Vue CLI Vuetify , tree-shaking is the default option: https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/dev/presets/default.json

**Comment by kevinmarrec** [comment]
Sounds right to be in `treeShake` mode by default and let user use `full` if it wants to through options ?

**Comment by MrJmpl3** [comment]
> Sounds right to be in `treeShake` mode by default and let user use `full` if it wants to through options ?

For me, sound good

**Comment by 1hakr** [comment]
Manual build mode is very much required. Currently the tree-shaking components are imported for every page even though they are not used.

**Comment by kevinmarrec** [comment]
I'm working on it @1hakr :)

https://github.com/nuxt-community/vuetify-module/pull/177
https://twitter.com/K_Marrec/status/1178039799078408192

**Comment by kevinmarrec** [comment]
Closed by https://github.com/nuxt-community/vuetify-module/pull/177 (possibility to disable automaticImports)
