### ISSUE TITLE
Nuxt throw error when updating to the latest version

### ISSUE THREAD

**Issue by jefrydco** [nuxt-community/vuetify-module#156]
**Module version**
1.7.0

**Describe the bug**
Running the latest version throws an error

**To Reproduce**

Upgrade the module to the latest version and nuxt building progress will throw an error as shown in the screen capture below.

**Expected behavior**
No error appeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/20434351/64490075-be7e2e80-d283-11e9-8cd8-d376909f04ed.png)

**Additional context**
-

**Comment by assoft** [comment]
I have the same problem

**Comment by kevinmarrec** [comment]
Working on a fix, sorry for the inconvenience

**Comment by kevinmarrec** [comment]
Please try **1.7.1** and ping me if it's correctly fixed.

**Comment by udanpe** [comment]
> Please try 1.7.1 and ping me if it's correctly fixed. 

Not work for me. 
Error: Template src not found: @nuxtjs/vuetify/dist/templates/plugin.js  
but current path /@nuxtjs/vuetify/templates/plugin.js

**Comment by kevinmarrec** [comment]
@udanpe Can you try replacing
`node_modules@nuxtjs/vuetify/dist/build.js` L27
`path.join(__dirname, '../templates', 'options.js')`
by
`path.resolve(__dirname, '../templates', 'options.js')` 
?

**Comment by kevinmarrec** [comment]
Nvm though you had options issue, but it's around `plugin` you have issue, but I don't understand why.
```
path.resolve(__dirname, '../templates', 'plugin.js')
```
should point to `@nuxtjs/vuetify/templates/plugin.js`

**Comment by kevinmarrec** [comment]
@udanpe I'm not sure you updated to last version, your error is from 1.7.0 and you're using custom options, so it was only failing on plugin (not options).

I'm not able to reproduce the issue locally unfortunately

**Comment by kevinmarrec** [comment]
My website https://marrec.io is hosted on Netlify and is using this module, and just bumping the new version fixed it for me:

![image](https://user-images.githubusercontent.com/25272043/64491571-58d17880-d26a-11e9-81e7-dbf7d25ec8e8.png)

**Comment by udanpe** [comment]
@kevinmarrec after replace to resolve  everything works.
1.7.0 does not have template folder. it's really 1.7.1. 
```npm remove --save @nuxtjs/vuetify && npm i -D @nuxtjs/vuetify@1.7.1```
<img width="816" alt="Screen Shot 2019-09-08 at 20 01 26" src="https://user-images.githubusercontent.com/7540232/64491633-7b1bc400-d273-11e9-9d29-d0fcda4b54e8.png">

**Comment by kevinmarrec** [comment]
My mistake, I think I've published without building 🤦‍♂️, should be fine with : **1.7.3**

**Comment by udanpe** [comment]
@kevinmarrec 1.7.3 without building too 
<img width="575" alt="Screen Shot 2019-09-08 at 21 33 50" src="https://user-images.githubusercontent.com/7540232/64492777-9d680e80-d280-11e9-8f95-c0754f94ef0e.png">

**Comment by kevinmarrec** [comment]
@udanpe Clean up and reinstall dependencies, you seemto have a broken `node_modules`

![image](https://user-images.githubusercontent.com/25272043/64492833-f3d14f00-d278-11e9-9ac2-d0c977a514e9.png)

**Comment by udanpe** [comment]
@kevinmarrec Thanks. After removing node_modules, package-lock and reinstall everything works.
