### ISSUE TITLE
Getting an error after updating to latest

### ISSUE THREAD

**Issue by lobo-tuerto** [nuxt-community/vuetify-module#159]
**Module version**
@nuxtjs/vuetify@^1.8.0

**Describe the bug**
I was on version "1.6.3" with no problems.
After doing `yarn add @nuxtjs/vuetify` and then running `yarn dev` I see:

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected ";".
  ╷
2 │ @import '~/assets/variables.scss'
  │                                  ^
```

**To Reproduce**
Just updated to latest version, because I wanted to update Vuetify to v2.0.15.

**Expected behavior**
It should not throw errors since it was working ok before updating.
If I rever to the previous version everything is OK.

**Comment by kevinmarrec** [comment]
Sounds like regression.
I've read something in the docs that `sass-loader` was now automatically applying the "indentedSyntax: true" for Sass files but it seems it just not work..

Could you try in nuxt.config 

```js
build: {
  loaders: {
    sass: {
      sassOptions: {
        indentedSyntax: true
      }
    }
  }
}
```
? Thanks !

**Comment by frbuceta** [comment]
> Sounds like regression.
> I've read something in the docs that `sass-loader` was now automatically applying the "indentedSyntax: true" for Sass files but it seems it just not work..
> 
> Could you try in nuxt.config
> 
> ```js
> build: {
>   loaders: {
>     sass: {
>       sassOptions: {
>         indentedSyntax: true
>       }
>     }
>   }
> }
> ```
> 
> ? Thanks !

I am with the same problem, I have implemented this and it works ;)

**Comment by kevinmarrec** [comment]
Okay, my bad then, will release a fix soon

**Comment by frbuceta** [comment]
> Okay, my bad then, will release a fix soon

Thanks Kevin

**Comment by kevinmarrec** [comment]
Released **1.8.1**, sorry for the inconvenience, was a mistake 😬

**Comment by iamareebjamal** [comment]
The process needs to improve. There are too many empty versions

**Comment by kevinmarrec** [comment]
@iamareebjamal Yeah sorry it's cause I was used to use `yarn standard-version` and then release. But now it needs to be compiled by TypeScriot so I created `yarn release` script which ensure tests and build before release.
