### ISSUE TITLE
Progressive image loading

### ISSUE THREAD

**Issue by dschreij** [nuxt-community/vuetify-module#167]
According to its docs, this module uses vuetify-loader under the hood. This loader has a nice feature of automatically generating progressive images (or low-res placeholders that are shown until the larger images have loaded), see https://github.com/vuetifyjs/vuetify-loader#progressive-images.

Does this module also support this feature out-of-the-box? I can't seem to find anything about it in the documentation, and it does seem to require some extra configuration to get it working if you manually need to set this up (e.g. adding `VuetifyProgressiveModule` to the compilerOptions of the webpack rule for vue-loader, and extending the rule for loading image types). Any directions on how to do this with this excellent module?

**Comment by kevinmarrec** [comment]
@dschreij Well you can extend webpack config and implement it on your own, but yeah it could be a nice out-of-the box feature.

**Comment by dschreij** [comment]
True, I have it working now in my previous method of including vuetify as a nuxtjs plugin. These are the only changes that I needed to make to my `nuxt.config.js`. Maybe you can use them as a lead once/if you decide to add this feature.

```javascript
const { VuetifyProgressiveModule } = require('vuetify-loader')
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

module.exports = {
  //...
  build: {
    //...
    extend (config, ctx) {
      ctx.loaders.vue.compilerOptions = {
        modules: [VuetifyProgressiveModule]
      }

      /** Alter img loading rules to use vuetify progressive loader */
      const imgRule = config.module.rules.find(
        r => r.test.toString() === '/\\.(png|jpe?g|gif|svg|webp)$/i');
      imgRule.oneOf = [imgRule.use[0]]
      imgRule.oneOf.unshift({
        test: /\.(png|jpe?g|gif)$/,
        resourceQuery: /vuetify-preload/,
        use: [
          'vuetify-loader/progressive-loader',
          {
            loader: 'url-loader',
            options: { limit: 8000 }
          }
        ]
      })
      delete(imgRule.use)
    }
  }
}


```

**Comment by kevinmarrec** [comment]
Hey @tschut , I planned to make it land in https://github.com/nuxt-community/vuetify-module/pull/177

And thanks to @dschreij that already provided a working implementation (did't try but he said it works) I should be able to provide it out of the box around the module as requested :)

**Comment by tschut** [comment]
Ok cool, I'm going to wait for 2.0 :) Couldn't get @dschreij snippet to work but I'm probably missing something obvious, my expertise on webpack is limited.

**Comment by kevinmarrec** [comment]
I didn't have the opportunity to try it out yet, all I know is that it requires `ImageMagick` to be installed on your machine (but I guess you already did cause I think you should have relevant error if not installed and trying to use the snippet).

**Comment by dschreij** [comment]
I'm not sure if it actually reports if ImageMagick is not found, or just fails silently. I also think the progressive loading only works on static/production builds, and not in the dev environment, but it's hard to say because images are of loaded very fast from the local machine.
To be honest, I didn't extensively test my implementation, so I don't know the edge cases. Before integrating my snippet in the module (if you plan on doing so at all), please review it carefully.

**Comment by kevinmarrec** [comment]
@dschreij Thanks for the informations ! Will take care of doing tests. I'll most likely implement my own solution but your snippet should be a good start ;)

**Comment by dschreij** [comment]
Haha, and I will bet it will be far better than mine. Webpack and JS builders are not my strongest suit. Thanks for all the hard work!

**Comment by tschut** [comment]
I did some quick testing, uninstalled ImageMagick and add @dschreij snippet again, but neither `yarn dev` nor `yarn build` fails, which is weird. I'm probably doing it wrong haha.

@dschreij I noticed in your snippet you have `const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')`, but it's not used anywhere. Is the snippet complete? You should be able to test if it works by using the Vue debug tools and inspecting the properties of the image component. It should include the placeholder I think.

**Comment by dschreij** [comment]
@tschut No it isn't, apologies. As I said, this snippet was taken from a nuxt project in which I integrated vuetify manually, thus without making use of @nuxt/vuetify. There I had to explicitly use the VuetifyLoaderPlugin, by adding the statement:

```javascript
config.plugins.push(
   new VuetifyLoaderPlugin()
)
```
but this part is taken care of by this module (I guess) and thus import of VuetifyLoaderPlugin is unnecessary.

**Comment by kevinmarrec** [comment]
@dschreij @tschut I'm stuck trying to implement the feature.
My build is outputing error (more likely an import one) whenever I do :
```js
modules: [VuetifyProgressiveModule]
```
around `vue-loader` compiler options :(

I'll probably postpone it to 2.1, module v2 is getting late

**Comment by tschut** [comment]
Can I help @kevinmarrec?

**Comment by kevinmarrec** [comment]
@tschut Well I would need a repository where someone succeeded to use Progressive Images inside a Nuxt project, cause I didn't.

**Comment by dschreij** [comment]
@kevinmarrec Do you refer to the error you posted earlier? Could you share the message? It took me a while to figure out how to get it to work too, but important is that you refer to all images with the absolute path from the project folder, using the @ to indicate the project root. For instance, for an image placed in `/static/img/someimg.jpg`, I first referred to it as:
```
<v-img  src="/img/someimg.jpg">
```
as /static can be used as the site root. The vuetify-loader however never picked this up, and I had to explicitly refer to this image as:

```
 <v-img  src="@/static/img/someimg.jpg">
```
Only then the progressive loading worked. I don't know if you already did it like this, but this was the main catch for me to get it working.

**Comment by dschreij** [comment]
@kevinmarrec I have made you contributor to a repository in which I have the progressive image loading working. I am not using the @nuxt/vuetify module in that repository but added vuetify the old-fashioned way as a plugin (I plan on using this module once progressive loading is working ;) ). Nevertheless, it may be useful for you to check out the nuxt.config.js. I hope it is of some use to you!

**Comment by dschreij** [comment]
As a side note, I opted to use GraphicsMagick instead of ImageMagick, because it's said to work more stable on Windows, so make sure that's present on your dev server (too) if it is to work.

**Comment by kevinmarrec** [comment]
@dschreij Thanks for your help , I'm gonna take a look !

**Comment by Pernick** [comment]
@kevinmarrec Hello Kevin, have you seen [this update 
to vuetify loader](https://github.com/vuetifyjs/vuetify-loader/releases/tag/v1.4.0-beta.0)?

**Comment by dschreij** [comment]
@Pernick that certainly is a nice update eliminating unnecessary complexity! I hope it helps making things easier.

**Comment by kevinmarrec** [comment]
Yeah I think we can just laverage https://github.com/vuetifyjs/vuetify-loader/pull/96/files# indeed, but as `vuetify-loader` plugin is not only used for automatic imports, it needs the Nuxt module API to be changed accordingly so there's gonna be breaking change, but all good as 2.0 is alpha for now

**Comment by kevinmarrec** [comment]
Implemented for next alpha release : https://github.com/nuxt-community/vuetify-module/commit/e5202844967431b2a0f769507cf4b489d17e9edc

**Comment by dschreij** [comment]
This is awesome. Thanks for all the hard work!

**Comment by tschut** [comment]
Hi, I was toying around with the 2.0.0-alpha.1 release, but progressive image loading didn't work for me out of the box. Do I need to enable it/does it need configuration?

**Comment by KaelWD** [comment]
> important is that you refer to all images with the absolute path from the project folder

It uses the same rules as vue-loader: https://vue-loader.vuejs.org/guide/asset-url.html

**Comment by tvld** [comment]
And what about ``nuxt.config.js``?  Anybody has an example how to configure there for Vuetify progressive images?
Also a bit stuck...

**Comment by Sshuichi** [comment]
Hi guys, how do we set the config for `nuxt.config.js`? @tvld Did you figure it out?

**Comment by tvld** [comment]
@Sshuichi I actually never did ... for now we skipped the progressive image loading completely ...

**Comment by coldze** [comment]
@Sshuichi @tvld I've got it working today, had to go through source code for `@nuxt/vuetify` and `vuetify-loader`... The solution is not obvious + I didn't find any related docs, but it turns out, that you can specify `vuetify-loader-options` through `vuetify.treeShake` (I had it set to `true`, but it also can be an object), so in my `nuxt.config.js` I've got it like this:

```
vuetify: {
    treeShake: {
      loaderOptions: {
        progressiveImages: true
      }
    },
    optionsPath: './vuetify.options.js'
  },
```

Just in case attaching simplified full `nuxt.config.js`:

```
const pkg = require('./package');
const gm = require('gm').subClass({appPath: '/usr/bin/'}); // <- gm didn't work without specifying a path, idk why

module.exports = {
  mode: 'spa',

  render: {},
  env: {},
  head: {},
  css: [],
  plugins: [
    {
      src: '@/plugins/vuetify',
      ssr: false
    }
  ],
  modules: [
    '@nuxtjs/vuetify',
    '@nuxtjs/axios'
  ],
  axios: {},
  router: {},
  vuetify: {
    customVariables: ['~/assets/style/generate_vars.scss'],
    treeShake: {
      loaderOptions: {
        progressiveImages: true
      }
    },
    optionsPath: './vuetify.options.js'
  },

  build: {}
};
```

**Comment by dschreij** [comment]
@coldze thanks for this. If it is this simple then I think this is a perfect solution until the next release of @nuxt/vuetify supports this natively.

Just out of curiosity, why do you also have a vuetify plugin if you also use the module?

**Comment by coldze** [comment]
@dschreij it's an artifact :) at some point code from that file was replaced with a different one, but the I was too lazy to rename it :(

**Comment by caseywittner** [comment]
@coldze does the above set up work with ImageMagick?
