### ISSUE TITLE
May I exclude Vuetify's global css?

### ISSUE THREAD

**Issue by r21nomi** [nuxt-community/vuetify-module#169]
I don't want to add Vuetify's global css(main.sass or vuetify.css) to my project since it overwrite my projects scoped style.

Until 1.0.0, there was `css` option to exclude the css file and the style was only applied to components by `treeShake: true`.
But css option [looks deleted](https://github.com/nuxt-community/vuetify-module/commit/6ff1910#diff-d1234a869b3d648ebfcdce5a76747d71L18-L19).

Is there any solution?

**Comment by kevinmarrec** [comment]
It should be something achievable with https://github.com/nuxt-community/vuetify-module/issues/154 `manual` mode. I will make it possible

**Comment by r21nomi** [comment]
`manual` mode looks good!!
I'm looking forward to using it.
Thanks.

**Comment by kevinmarrec** [comment]
Closing in favor of #154 that will be soon implemented
