### ISSUE TITLE
Theme not applied after updating to Vuetify 2.0

### ISSUE THREAD

**Issue by davidVenegas** [nuxt-community/vuetify-module#171]
**Module version**
1.8.5

**Describe the bug**
After following the MIGRATION_GUIDE all the colors from vuetify are not working, not even the default Vuetify theme. All the "primary, error, info, warning, ..." colors are always displaying "#f5f5f5"

This is the actual configuration for vuetify inside nuxt.config.js:

![Selection_223](https://user-images.githubusercontent.com/40215990/65450009-d3b99800-de01-11e9-891f-24108fa73b64.png)

**To Reproduce**
Update @nuxtjs/vuetify from 0.5.5 to 1.8.5 and follow the MIGRATION_GUIDE.

**Expected behavior**
After updating all the component for matching the new Vuetify 2.0 the only thing missing are all the colors for the entire app.

**Screenshots**
This is the way all the buttons and components are being displayed:
![Selection_224](https://user-images.githubusercontent.com/40215990/65450151-19766080-de02-11e9-8ab6-a6eabf60e3e7.png)

**Additional context**
I've been trying to solve it but with no luck.
I already uninstall an re install @nuxtjs/vuetify with all the dependencies.
Try the plugin way but with the same result.
Maybe I'm missing some library, I already installed **sass** and **sass-loader** using **npm** with the same result.

Thanks in advance.

**Comment by kevinmarrec** [comment]
@davidVenegas Please provide a repository with this issue, I'll dive into it :)

**Comment by kevinmarrec** [comment]
Try to reproduce it with minimal setup

**Comment by davidVenegas** [comment]
I'm working on a private repository and don't have the permissions for giving others access. Sorry.

I tried with no configuration at all, the same result.

![Selection_225](https://user-images.githubusercontent.com/40215990/65450975-e92fc180-de03-11e9-9061-c63ed78ff4c7.png)

**Comment by kevinmarrec** [comment]
Well I won't be able to help further if I can't reproduce the issue with some code base.
All I can say it's for your first screenshot if should be `theme.themes`, not `theme.theme`.

**Comment by davidVenegas** [comment]
Well, finally we could solve it, the problem was that I had installed two different versions of @nuxtjs/vuetify and I think they were conflicting.

In my package.json in **dependencies** I had:

`"@nuxtjs/vuetify": "^0.5.5"`

and in **devDependencies** I had:

`"@nuxtjs/vuetify": "^1.8.5"`

So I delete the one from **devDependencies** and update the version to **1.8.5** in **dependencies** reinstall everything and it's working now.
