### ISSUE TITLE
It seems css files in nuxt.config.js are overriden by vuetify

### ISSUE THREAD

**Issue by fhcj2** [nuxt-community/vuetify-module#176]
Whenever I add css files to the "css" array in nuxt.config.js I can see they are loaded via browser inpector but are actually overriden by Vuetify styles though.

I there a way to turn this around, i.e. to **make the files in nuxt.config.js css option actually override Vuetify's ones**?

**Comment by kevinmarrec** [comment]
@fhcj2 What are the specific styles overriden ?
You may want to use https://github.com/nuxt-community/vuetify-module#customvariables ?

**Comment by fhcj2** [comment]
I tried that way as well and the css won't even load that way. You can check it in this repo: https://codesandbox.io/s/nuxtjs-vuetify-s6cdo

I'm trying to ovrride vuetify's html overflow attribute for now, did it in both mainmain.scss and variables.scss as a test. The one from mainmain.scss is actually loaded but overriden by Vuetify, and the one from variables.scss won't even load

**Comment by kevinmarrec** [comment]
@fhcj2 `html` overflow override need to be set as `!important`, it's a specific case.

**Comment by kevinmarrec** [comment]
And you can't do it thorugh custom Vuetify variables, it needs to be done in `assets/whatever.css` and being imported in `config.css` array

**Comment by kevinmarrec** [comment]
https://github.com/kevinmarrec/marrec.io/blob/master/assets/style/app.scss
https://github.com/kevinmarrec/marrec.io/blob/master/assets/style/app.scss

**Comment by fhcj2** [comment]
> And you can't do it thorugh custom Vuetify variables, it needs to be done in `assets/whatever.css` and being imported in `config.css` array

@kevinmarrec Isn't that what I did by adding the mymain.scss into nuxt.config.js -> css array?



> @fhcj2 `html` overflow override needs to be set as `!important`, it's a specific case.

Why would that be needed in case the css is (supposedly) loaded after Vuetify css? Also it seems to not work for any override I try to make over vuetify whatsoever; for instance, I tried to make the following override without success in [here](https://codesandbox.io/s/nuxtjs-vuetify-0k05s):

`.v-list-item__title {
  font-size: 30pt;
}`

**Comment by kevinmarrec** [comment]
@fhcj2 Vuetify css is loaded after, I'm not sure yet what's the correct way to override Vuetify classes.
Custom SASS variables will work cause Vuetify use a `default` SASS keyword that only set a variable if it hasn't be set before.

**Comment by fhcj2** [comment]
@kevinmarrec Oh, i see. Vuetify is really loaded after my styles then, is there a reason to it? Could it be done the other way around?

Seems kinda messy to me that I have to keep using !important and overspecifying my selectors over Vuetify since it already overspecifies its own selectors a lot already. There're Vuetify selectors with over 4 classes selectors for instance, so I have to specify it even further to get to override it. Also, any more generic selector like "html" overrides my own and have to use !important to remedy it, or add classes (specificity) to it. That would mean any Vuetify change to these generic selectors could get me by surprise and override my own selectors as well and I'd have to keep extra attention to these changes.

**Comment by kevinmarrec** [comment]
@fhcj2 There isn't way AFAIK, in components you can also use deep selector : https://vuedose.tips/tips/style-inner-elements-in-scoped-css-using-deep-selector-in-vue-js/

Css given to `css` array of Nuxt config are considered as inline critical CSS, so they will be put in top of HTML file in `head` and loaded first.

Then, Vuetify components used in pages are more likely loaded by Nuxt client side OR anyway there css is preloaded in `head` too but after critical CSS. Which means there isn't really a way to override Vuetify classes.

I know that Vuetify is working on adding tons of new SASS variables to be able to customize things more easily.

Well, if you're overriding Vuetify css, it's your job to keep extra attention on any CSS change of the framework. I think it's normal.

**Comment by fhcj2** [comment]
@kevinmarrec I see. It still seems weird to me but since there's no way around I'll keep doing the things I mentioned then. Thank you kevin!

**Comment by kevinmarrec** [comment]
@fhcj2  I'm gonna close this issue for now, you can still open an issue on Nuxt repo to ask for a more general solution regarding overriding css of third parties :)

**Comment by Thanhnt1** [comment]
Thanks for your info Kenvin

**Comment by pawel-marciniak** [comment]
Any solution to this in newer version?

**Comment by bchellingworth** [comment]
A quick work around:

Create component called "StyleLoader" (or whatever), in the <style "lang=scss"> import your custom scss.

```
<template>
</template>

<script>
export default {
name: "StyleLoader"
}
</script>

<style lang="scss">
	@import "../your/custom/scss";
</style>
```

In App.vue import the StyleLoader component and put it at the end of page after all the vuetfiy components.

Any styles in your custom scss will be loaded after vuetify.
