### ISSUE TITLE
Using CustomVariables in Dev?

### ISSUE THREAD

**Issue by hondnl** [nuxt-community/vuetify-module#181]
For example, if I would like to change the default colors **AND** the background color in Vuetify.

```
 vuetify: {
    customVariables: ['~/assets/variables.scss'],
    theme: {

      themes: {
        light: {
          primary: '#3EA0E1', // a color that is not in the material colors palette
          accent: '#82B1FF',
          secondary: '#E7E7DE',
          info: '#1976D2',
          error: "#FF5252",
          success: "#4CAF50",
          warning: "#FFC107",
        }
      }
    },

  },
```

and in  ~/assets/variables.scss

```
@import '~vuetify/src/styles/styles.sass';
$material-light: map-merge($material-light, ( background: '#fff'));

```

Now I gathered that tree shaking ( and using those custom vars ) only is available in production.
Is it possible to use the changed variables ( like a simple background color) in dev mode?
I don't care that in dev all the vuetify components are loaded ( and not threeshaken), but I would like to use this changed stylesheet-vars.
Is there a way , like there was in 1.*

**Comment by kevinmarrec** [comment]
@hondnl No it's not possible for the simple reason that without tree shaking, full `dist/vuetify.js` and `dist/vuetify.css`. CSS already have been processed and can't be changed by SASS.

Custom variables need to be handled with treeShaking so that during webpack build, your custom SASS variables are "injected" in Vuetify SASS.

You can still try to override directly Vuetify color classes but that's not the correct way cause it would be really painful and could easy break in next Vuetify versions.

So as mentioned in documentation, treeShaking is mandatory to be able to customize the Vuetify SASS variables.

FYI, `treeShake` will be removed in **2.0** version of this module, find more information here : https://github.com/vuetifyjs/vuetify/blob/dev/packages/vuetify/src/services/theme/index.ts#L183

**Comment by hondnl** [comment]
So wait a minute , you are telling me since vuetify 2 , I have to re-build my whole app every time I want to see a small design/app change  ? 
Or i am stuck with a grey background and any other default setting one might want to change ( like basic font colors?).
Hmm far from ideal I must say...

Thanks for your fast reply

**Comment by kevinmarrec** [comment]
@hondnl Well overall build time is increased cause of `vuetify/lib` transpilation, this transpilation won't be able to be skipped in next module version. It is also how works the Vue CLI Vuetify plugin.

If you then change something in your project, it will depend what exactly you'll be changing, it may trigger a full Nuxt restart which may transpile again `vuetify/lib`.

Also, Vuetify 2 has been thought treeshakable by default, so to customize SASS variables it seems logic there is somewhen in your build process that your custom variables are handled by Vuetify to update component CSS. So yes it has to rebuild all css of the components.

**Comment by hondnl** [comment]
@kevinmarrec  : thanks for your explanation... 

For now , while building the base design of my app I will overwrite the vuetify.css  for dev...
I don't need a lot of changes, just some basic colors and such...  see how that goes.
Once I am far enough in the app , I will build && serve like suggested.
Bad practice, but it will remove hours of waiting if I cannot use hot-reloading.

```
// assets/devCustomVars.css
@import '..\\node_modules\\vuetify\\dist\\vuetify.css';

.theme--light.v-application {
  background: red;
}

```
And In your build.js

```

if (!options.treeShake) {
         // this.options.css.push('vuetify/dist/vuetify.css');
       // new one..
        this.options.css.push('~/assets/devCustomVars.css');
    }

```

**Comment by kevinmarrec** [comment]
@hondnl It seems https://github.com/vuetifyjs/vue-cli-plugin-vuetify/releases/tag/v1.0.0 is showcasing some new behavior to deal with custom variables, I'm planning to use similar logic within this module. It may fix your use case.

**Comment by kevinmarrec** [comment]
Also, `vuetify/dist/vuetify.css` statement will be removed in next version of this module, so you should be able to properly use your behavior :)

**Comment by hondnl** [comment]
Thanks a lot Kevin , much appreciated all the work you put into this.

**Comment by kevinmarrec** [comment]
I think it should be resolved with https://github.com/nuxt-community/vuetify-module/pull/177 
Please look at https://github.com/nuxt-community/vuetify-module/releases/tag/v2.0.0-alpha.0
