### ISSUE TITLE
Errors after upgrading to nuxt@2.10.0 and @nuxtjs/vuetify@1.9.0

### ISSUE THREAD

**Issue by seth100** [nuxt-community/vuetify-module#182]
**Module version**
@nuxtjs/vuetify@1.9.0

**Describe the bug**
I have just upgraded to `@nuxtjs/vuetify@1.9.0` and `nuxt@2.10.0` from latest previous version. No code changes in my application.

My application does not load anymore, I get many errors (see the screenshot).

**Expected behavior**
My web application should work as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/4366877/66075758-8dc8a680-e55c-11e9-840c-c01fe7c2cff7.png)

Any help please?
Thanks

**Comment by kevinmarrec** [comment]
Hi @seth100 , please see https://github.com/vuetifyjs/vuetify/issues/9181

**Comment by seth100** [comment]
Hi @kevinmarrec , thank you for the info, I will wait for the Nuxtjs fix
