### ISSUE TITLE
this.$vuetify undefined at version 2.10.0 of Nuxt

### ISSUE THREAD

**Issue by abarkhurst** [nuxt-community/vuetify-module#183]
**Module version**
v1.9.0

**Describe the bug**
this.$vuetify is undefined at the new 2.10.0 version of Nuxt

running in npm run dev mode does not cause an issue on my local environment but when I pushed a yarn build onto production the error occurred in two of the applications that I have running.

**Comment by kevinmarrec** [comment]
@abarkhurst Are you aware of https://github.com/vuetifyjs/vuetify/issues/9181 ?
Also providing a reproduction repository always help ^^

**Comment by abarkhurst** [comment]
> @abarkhurst Are you aware of [vuetifyjs/vuetify#9181](https://github.com/vuetifyjs/vuetify/issues/9181) ?
> Also providing a reproduction repository always help ^^

I was not aware of that. My apologies! I figured it was a rookie mistake on my part and something that I was just missing. Sorry and thank you! I love the project!
