### ISSUE TITLE
Vuetify directives support

### ISSUE THREAD

**Issue by Elvanos** [nuxt-community/vuetify-module#188]
**Is your feature request related to a problem? Please describe.**
I was unable to get `v-touch` to work with this package while trying to use it inside Vuetify components.
My assumption (possibly wrong one) is that this either got broken in some new Vuetify version or never had support to begin with.

**Describe the solution you'd like**
Either some automatic support or manual-cherry picking for supported directives from Vuetify via the config.

**Describe alternatives you've considered**
I tried using the nuxt plugins directory with some workaround I found on the git issues of Vuetify - without success.

**Additional context**
![directives](https://user-images.githubusercontent.com/16904898/66350684-4414fd00-e95c-11e9-8cdf-641e4a45d78f.png)

**Comment by kevinmarrec** [comment]
@Elvanos It is not documented 🤦‍♂️but you should be able to do :

```ts
vuetify: {
  treeShake: {
    directives: ['touch'] 
  }
}
```

It will be changed to a new behavior with #177 (see **Global Imports** section)

**Comment by kevinmarrec** [comment]
You can also locally import the directive in your Vue SFC and tell to your component to register it so it's accessible only within your component.

**Comment by Elvanos** [comment]
@kevinmarrec Thank you for the help. I managed to get it to work via the SFC import solution. 
However, your first, global suggestion did not work for me at all.

My SFC ended having this code added:

```
import { Touch } from "vuetify/lib/directives"

  directives:{
    Touch
  }
```

**Comment by kevinmarrec** [comment]
@Elvanos Oh yeah sorry, should be 
```js
directives: ['Touch']
```
not
```js
directives: ['touch']
```

**Comment by Elvanos** [comment]
Very nice! This fixed it in all instances. Thank you for the help :)

**Comment by vahid-traceur** [comment]
> @Elvanos It is not documented but you should be able to do :
> 
> ```ts
> vuetify: {
>   treeShake: {
>     directives: ['touch'] 
>   }
> }
> ```
> 
> It will be changed to a new behavior with #177 (see **Global Imports** section), (overall it will just be about renaming/moving module options)

thank you very much, it helps me to solve m problem
