### ISSUE TITLE
Need support for mdiSvg icon implementation

### ISSUE THREAD

**Issue by avanishp2** [nuxt-community/vuetify-module#197]
**Problem Description**
If you put **mdiSvg** in icons section then all the default icons of vuetify components get vanish and still uses the **mdi** version of icon syntax. 
```
vuetify: {
        customVariables: ['~/assets/variables.scss'],
        defaultAssets: {
            font: false,
            icons: 'mdiSvg'
        },
        treeShake: true
    },
```
**What should be accepted**
**icons** should accept mdiSvg as option and default icons of all vuetify components should work as per vuetify official doc. [vuetify icon presets](https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/services/icons/presets)

**What I have Done for work around**
I have used **mdi/js** to use bunch of icons for my project as per vuetify official doc. But for default icons also I need to set the icon manually for each and every vuetify component I am using...which is very frustrating. e.g. <v-app-bar-nav-icon>, <v-rating>, <v-select> etc.

**Comment by kevinmarrec** [comment]
@avanishp2 Well in fact `defaultAssets.icons` should automatically change `icons.iconfont` framework option through : https://github.com/nuxt-community/vuetify-module/blob/master/src/build.ts#L46 and https://github.com/nuxt-community/vuetify-module/blob/master/templates/plugin.js#L35, resulting in generated Nuxt plugin :
![image](https://user-images.githubusercontent.com/25272043/67007881-a4d4d000-f0e8-11e9-872d-b9beb805b7c9.png)

So please provide a reproduction :D

**Comment by avanishp2** [comment]
@tschut your way of declaring icons worked for me. Thanks for the suggestion :+1: 

@kevinmarrec Yes it should but it is not using the default mdiSvg icon set. Will post reproduction code when I will get time as I am busy building my own product.
