### ISSUE TITLE
Using Vuetify sass variables in components

### ISSUE THREAD

**Issue by mckraemer** [nuxt-community/vuetify-module#204]
I would like to know how I can use default Vuetify sass variables in my components.
I have already asked that on Vuetify Discord, unfortunately they could not helpe me with that issue in combination with nuxt. I would like to use the default breakpoints in my sass code.
Thanks for any help! :)

**Comment by dschox** [comment]
hi, I wrote to you on Discord... have you tried with a fresh install of nuxt and vuetify module?
I migrated from vuetify 1.5 to 2 with this module and can use the variables from vuetify everywhere (scss files and style blocks of SingleFileComponents)...
Could you show your deps?

**Comment by mckraemer** [comment]
Hi,
I have tried a clean installation of nuxt. It wasn't working for me.

**Comment by kevinmarrec** [comment]
@mckraemer Any code with reproduction ? Or snippet or what you're trying to do ?
I'm not sure it's really Nuxt related
