### ISSUE TITLE
Is there any way to fix css loading after page load when i use generate mode?

### ISSUE THREAD

**Issue by SLIpros** [nuxt-community/vuetify-module#210]
**Module version**
Nuxt.js@2.10.2
@nuxtjs/vuetify@1.9.0

Hey, i am using generated version of nuxt. My css load after page load
This is how it looks like - https://www.youtube.com/watch?v=KzYxmJIAe9I
Page address - https://boost.ninja
Any way to load css with page?

**This is my nuxt build config**
```
build: {
	splitChunks: {
		layouts: true,
		pages: true,
		commons: true
	},
	transpile: [
		'@rabota/analytics-layer',
		'@rabota/yandex-metrika',
		'vuetify/lib',
	],

	extractCSS: true,
	/*
		** You can extend webpack config here
		*/
	extend(config, ctx) {
		// Run ESLint on save
		if (ctx.isDev && ctx.isClient) {
			config.module.rules.push({
				enforce: 'pre',
				test: /\.(js|vue)$/,
				loader: 'eslint-loader',
				exclude: /(node_modules)/
			})
		}
	}
}
```

**Comment by kevinmarrec** [comment]
@SLIpros Did you consider build.`extractCSS` option, see : https://github.com/nuxt-community/vuetify-module/issues/208#issuecomment-548615718

**Comment by SLIpros** [comment]
@kevinmarrec I am already using it, look at my config. This thing start happens after vuetify release v2.

**Comment by SLIpros** [comment]
I fixed issue! Delete this part from build config.
```
splitChunks: {
	layouts: true,
	pages: true,
	commons: true
},
```

This is how my current build config looks like
```
build: {
	transpile: [
		'@rabota/analytics-layer',
		'@rabota/yandex-metrika',
		'vuetify/lib',
	],
	extractCSS: true,
	extend(config, ctx) {
		// Run ESLint on save
		if (ctx.isDev && ctx.isClient) {
			config.module.rules.push({
				enforce: 'pre',
				test: /\.(js|vue)$/,
				loader: 'eslint-loader',
				exclude: /(node_modules)/
			})
		}
	}
}
```
