### ISSUE TITLE
maintain shade (dark/light) and theme color on browser (re)load

### ISSUE THREAD

**Issue by ssglopes** [nuxt-community/vuetify-module#212]
**Feature or existing problem**
To maintain shade (dark/light) and theme color on browser load when these where previously saved inside a cookie by user interaction instead of first loading the default shade and theme color which are passed as module options

**Requested solution**
Example:
- User cookie contains: light shade with orange theme color
- Default fallback (as passed by the module options): dark shade with blue theme color
 
Situation 1: When cookie is absent on browser load the page will load directly with dark shade and blue theme.
Situation 2: When above cookie is found browser should load directly with light shade and orange theme color.
Situation 3: When above cookie is found browser instead loads first with dark shade and blue theme color and than by means off a plugin, is than updates to light shade with orange theme color. This short transition can been seen on each browser (re)load.

Situation 2 should be the preferred way forward and NOT situation 3.
  
**Alternatives tried**
Alternative 1: Not using `@nuxt/vuetify` as than we can control when `new Vuetify(options)` is executed and so we can pass the correct options as we are able to read the cookies before the actual options object is created and passed to `new Vuetify()`. 
Alternative 2: Using `@nuxt/vuetify` (preferred) with options object `{ theme: { disable: true, ...}}`
and setting the light/dark shade and theme color by means of a plugin during SSR. 

**Problem**
With approach 2:  `disabled: false` execution fails because a call to [document.xxxx](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/theme/index.ts) on ssr is not possible and with `disabled: true` all the dark and light color variants are not calculated as this is skipped in the [constructor] and as a consequence these colors are than missing in the browser under `:root var(--v-primary-darken1)` (https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/theme/index.ts)

**Comment by kevinmarrec** [comment]
What about a module option which would be a function that returns a theme ?
It would be merged in framework options and the `process.client`/`process.server` (for SSR) could be handled by user with his custom function

**Comment by kevinmarrec** [comment]
FYI it's already possible with https://github.com/nuxt-community/vuetify-module#optionspath

You just need the file to return a function and write your logic that returns the correct framework options, you have here access to Nuxt context, which means access to `req`  to grab SSR cookies.

**Comment by Radiergummi** [comment]
@kevinmarrec could you provide an example for this? I'm trying to get this working, but the options function is never invoked and the loading times have quadrupled. Not sure if that's just ordinary Nuxt performance shenanigans or related to the Vuetify config. Anyway, an example in the documentation would be highly appreciated.
