### ISSUE TITLE
How to do "reference module when needed" in nuxt?

### ISSUE THREAD

**Issue by snoopy83101** [nuxt-community/vuetify-module#215]
There are too many vuetify modules.
I only use a small part of it.
How to do "reference module when needed" in nuxt?

**Comment by tschut** [comment]
With a production build, treeshaking is enabled by default. I.e. modules that aren't used won't be included in the production build.

**Comment by snoopy83101** [comment]
@tschut 

Thank you for your answer!
The default css is in node_models.
If I don't want to reference css in node_models.
I want to introduce it in CDN: https://cdn.staticfile.org/vuetify/2.1.1/vuetify.min.css

How can we do it?

**Comment by kevinmarrec** [comment]
@snoopy83101 Treeshaking automatically bundle the minimal css (only css of modules you're using), full Vuetify CSS and you really don't want to have the full css in production.

**Comment by kevinmarrec** [comment]
WIth the 2.0.0-alpha of the module you can also disable `automaticImports` and import Vuetify components on your own everywhere like described here : https://vuetifyjs.com/en/customization/a-la-carte#manually-importing

**Comment by ManasMadrecha** [comment]
@kevinmarrec Treeshaking automatically remove unused components and bundles the minimal css, but it still includes css of components I am not using anywhere in my website. Any suggestion?
