### ISSUE TITLE
Allow default font weight customization

### ISSUE THREAD

**Issue by mzenz** [nuxt-community/vuetify-module#216]
Currently Nuxt's Vuetify plugin hardcodes the default font's font weights to a predefined set. This forces apps to pull more typefaces than needed, thus slowing down download times, and also some of those predefined weights might not even be available for all fonts:

https://github.com/nuxt-community/vuetify-module/blob/3ce0a7d51dfb95f9e312feffe6faae40469fe37d/src/font.ts#L9

It would be nice if there was an option to customize this as well so that only the desired/needed font weights can be downloaded from the CDN.

Alternatively, there could be a way to disable pulling any fonts and leave it up to the developer to pull the desired font resources via nuxt.config.js "link" attribute.

I'd be happy to take a stab at this if you want, let me know.

**Comment by kevinmarrec** [comment]
@mzenz Well you can't properly do that, all different font-weights are used across multiple internal Vuetify component CSS. So you'll have display issue for sure.

**Comment by mzenz** [comment]
@kevinmarrec Good point, thanks for getting back. I now see that those hardcoded font weights match the predefined font weights inside Vuetify's _variables.scss.

Closing.
