### ISSUE TITLE
Images in assets folder not found when using v-img component

### ISSUE THREAD

**Issue by jimb0dii** [nuxt-community/vuetify-module#220]
**Module version**
@nuxtjs/vuetify@1.9.0
nuxt@2.10.2

**Describe the bug**
Using "~url" syntax to access an image within assets folder doesn't work inside v-img component.

**To Reproduce**
1. Add an image in assets folder
2. Access that image inside v-img

**Expected behavior**
The image should be displayed

**Screenshots**
Current Code
![image](https://user-images.githubusercontent.com/27861727/69130151-fce96280-0aea-11ea-9345-ea100b7ad78b.png)

Code Output
![image](https://user-images.githubusercontent.com/27861727/69130224-17bbd700-0aeb-11ea-8465-7a14009d082c.png)

**Additional context**
NA

**Comment by Codefa** [comment]
Hi @jimb0dii  **Try like this**  
`<v-img :src="require('~/assets/images/background-1.jpg')" />`

**Comment by jimb0dii** [comment]
> Hi @jimb0dii **Try like this**
> `<v-img :src="require('~/assets/images/background-1.jpg')" />`

Thanks it works.

**Comment by Codefa** [comment]
@jimb0dii please close the issue if it's work's fine. 🙂
