### ISSUE TITLE
Fibers missing implement

### ISSUE THREAD

**Issue by MrJmpl3** [nuxt-community/vuetify-module#227]
**Module version**
1.9.1

**Describe the bug**
I look the code and don't implement the fibers plugin in sass loader ..

https://www.npmjs.com/package/fibers

https://github.com/nuxt-community/vuetify-module/blob/master/src/sass.ts

**Comment by VRuzhentsov** [comment]
Facing the same issue when trying to test app with jest

**Comment by kevinmarrec** [comment]
@MrJmpl3 `fibers` is automatically used if found since `sass-loader@8` https://github.com/webpack-contrib/sass-loader/releases/tag/v8.0.0
