### ISSUE TITLE
Using vuetify.breakpoint break DOM

### ISSUE THREAD

**Issue by devalexqt** [nuxt-community/vuetify-module#235]
**Module version**
The version of the module you're using.
@nuxtjs/vuetify 1.9.1

**Describe the bug**
Using `v-if="$vuetify.breakpoint.smAndUp"` in element cause error.

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`
**To Reproduce**

https://codesandbox.io/s/nuxtjs-vuetify-y7fj4
1. add `v-if="$vuetify.breakpoint.smAndUp` to v-btn element
2. Watch console for error `[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

**Expected behavior**
No errors or warnings in console.

**Comment by aldarund** [comment]
Its not a bug in module. Its how vuetify and ssr works. See https://github.com/vuetifyjs/vuetify/issues/3436  for some workarounds.

Basically server dont know what screensize and so dont know what breakpoint to use. And client rendered should be same as server rendered, and its impossible if u you just use breakpoint in template.
