### ISSUE TITLE
Please upgrade Vuetify to 2.2.x

### ISSUE THREAD

**Issue by AGDholo** [nuxt-community/vuetify-module#236]
**Is your feature request related to a problem? Please describe.**
Vuetify 2.2.x has been released, and publish a [Presets](https://vuetifyjs.com/en/customization/presets/) feature.

**Describe the solution you'd like**
Smooth update and import VuetifyPreset.

**Describe alternatives you've considered**

**Additional context**
https://vuetifyjs.com/en/customization/presets/  
https://github.com/vuetifyjs/vuetify/releases

**Comment by frck006** [comment]
Same problem:
![image](https://user-images.githubusercontent.com/10244725/71716202-37e1f400-2e14-11ea-8fcf-ff6066c6f9a5.png)

**Comment by SuhwanCha** [comment]
+1

**Comment by clixmat** [comment]
Hi @kevinmarrec , please help us with the update, I have problems installing, request a preset ...
![bug-01](https://user-images.githubusercontent.com/41817274/71761519-56d69980-2e99-11ea-8861-d0f510b86d72.PNG)
![bug-02](https://user-images.githubusercontent.com/41817274/71761520-56d69980-2e99-11ea-9b5f-6a43ba737801.PNG)

**Comment by designzoo-adrian** [comment]
I too am receiving an error running my Nuxt project with Typescript enabled using @nuxtjs/vuetify@1.9.1. I did a recent reinstall a few days ago, which I think coincided with the 2.20 release of Vuetify.

<img width="768" alt="Screenshot 2020-01-04 at 11 56 58" src="https://user-images.githubusercontent.com/1336717/71765190-5fef5700-2ee9-11ea-9eb1-40306464d9e9.png">

Error seems to be coming from the options.ts file.

The path seems to now required to be  "vuetify/types/services/presets"

**Comment by aldarund** [comment]
How are you getting this errors? When trying to use presets or its out of box? I have updated vuetify to 2.2 in my project and dont have errors, although i dont use presets yet

**Comment by clixmat** [comment]
> How are you getting this errors? When trying to use presets or its out of box? I have updated vuetify to 2.2 in my project and dont have errors, although i dont use presets yet

No, just install the nuxt-vuetify, place the buidmodules and try to run npm run dev and it gives that error.

**Comment by aldarund** [comment]
@clixmat no errors for me in my ts project. I even tried new empty project with create nuxt app and still was fine. Please provide a reproduction.
I think  you might have two different version of vuetify in your deps and that leads to problem, try to delete your node modules and lock file and reinstall. If problem still persist -> provide a minimal reproduction

**Comment by designzoo-adrian** [comment]
I deleted my node_modules folder and lock file and resintalled everything from scratch. I still get the error on _npm run dev_

I found out I only receive the same error 
![image](https://user-images.githubusercontent.com/1336717/71779093-a22d9c80-2fac-11ea-9154-71696ea15e1f.png)
only when I add the following types reference "@nuxtjs/vuetify" to my tsconfig file compilerOptions as per the typescript support documentation here. (https://www.npmjs.com/package/@nuxtjs/vuetify#typescript)

**Comment by aldarund** [comment]
Ye, indeed adding @nuxtjs/vuetify breaks it

**Comment by reilue** [comment]
Sorry to reopen this. Do you know how to actually include Preset in nuxt.config.js.
I could successfully import the module, but idk how to include Preset.
Thanks!
