### ISSUE TITLE
Using defaultAssets with the OptionsPath doesn't work

### ISSUE THREAD

**Issue by ianfortier** [nuxt-community/vuetify-module#245]
**Module version**
    "@nuxtjs/vuetify": "^1.9.1",

**Describe the bug**
When you are using a custom optionsPath the defaultAssets isn't working.
I tried to change the font-family as described in the docs by setting the defaultAssets.font.family: "Raleway", but the font wasn't changing... I figure out that you need to set the defaultAssets in the nuxt.config directly otherwise the option won't work.

**To Reproduce**
Set the defaultAssets in a optionsPath file

**To Fixed**
Set the defaultAssets in the nuxt.config directly

**Expected behavior**
Being able to set the defaultAssets in the custom option file

**Comment by kevinmarrec** [comment]
@ianfortier It's specified in documentation that `optionsPath` is for Vuetify (the framework) options : https://github.com/nuxt-community/vuetify-module#optionspath

`defaultAssets` is a **module** option, not a **framework** option, so it should be kept in `nuxt.config.js`.

Options in the file specified by `optionsPath` should only contains Framework options like `theme`, `breakpoint`, `icons`, ...

**Comment by ianfortier** [comment]
Make sense! Thank you!

**Comment by PJLindsay** [comment]
Documentation says to set defaultAssets: false

in your nuxt.config.js:
buildModules: [

  ['@nuxtjs/vuetify', { defaultAssets: false, }]
