### ISSUE TITLE
Unable to import from 'vuetify/lib' in `vuetify.options.js` (dev mode)

### ISSUE THREAD

**Issue by andrewspy** [nuxt-community/vuetify-module#248]
**Module version**
1.9.1

**Describe the bug**
Browser will show error after importing from 'vuetify/lib' in nuxt dev mode (no problem in production mode)

Browser error:

```
SyntaxError
Unexpected token export
```

**To Reproduce**

1. Add following line to `vuetify.options.js`

```js
import { VImg } from 'vuetify/lib';
```

2. Run `nuxt` (no error on console)
3. Visit `http://localhost:3000`
4. See error on the browser.

**Expected behavior**
Able to import from 'vuetify/lib' without error in the browser.

**Additional context**
There seems to be no problem in production mode (i.e. `nuxt build/start`), only having problem using `nuxt` in dev mode.

**Comment by kevinmarrec** [comment]
@andrewspy Afaik it's not possible to use import from `vuetify/lib`, you need to import from `vuetify/es5` instead

**Comment by andrewspy** [comment]
@kevinmarrec In my case, I need to register `VImg` globally, and importing from `vuetify/lib` is as per the [official guide](https://next.vuetifyjs.com/en/customization/a-la-carte#markup-js-a-la-carte-manual).

As for my `treeShake`, I am not setting it (i.e. using as default).

**Comment by Janne252** [comment]
You'll have to configure `nuxt` to transpile `vuetify/lib` using [`build.transpile`](https://nuxtjs.org/api/configuration-build/#transpile) property:

**nuxt.config.js**
```ts
export default {
	// ...
	build: {
		transpile: ['vuetify/lib'],
	},
	// ...
}
```

**Comment by andrewspy** [comment]
@Janne252 I managed to get it to work with the `build.transpile` property. Thanks!

I shall close the issue, but I think it should be documented in the `vuetify-module` doc.

**Comment by kevinmarrec** [comment]
https://github.com/nuxt-community/vuetify-module/blob/master/src/build.ts#L15

`vuetify/lib` transpilation is handled but as it makes build slower it's only enabled with `treeShake` is enabled.
