### ISSUE TITLE
optionsPath not working

### ISSUE THREAD

**Issue by robsontenorio** [nuxt-community/vuetify-module#252]
**Module version**
master

**Describe the bug**
The `optionsPath` does not work as expected, as described on README. Hot reloading not watching for changes

**To Reproduce**
See additional context

**Expected behavior**
Should compile when `vuetify.options.js` changes

**Additional context**

/vuetify.options.js on root folder
```js
import colors from 'vuetify/es5/util/colors'

export default {
  frameworkOptions: {
    theme: {
      dark: true,
      themes: {
        light: {
          primary: colors.yellow.accent1,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        }
      }
    }
  }
}
```

nuxt.config.js

```js
export default {
  mode: 'spa',
  /*
  ** Headers of the page
  */
  head: {
    titleTemplate: '%s - ' + process.env.npm_package_name,
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },
  /*
  ** Global CSS
  */
  css: [
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/eslint-module',
    '@nuxtjs/vuetify',
    '@nuxtjs/dotenv'
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    '@nuxtjs/axios'
  ],
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
  },
  /*
  ** vuetify module configuration
  ** https://github.com/nuxt-community/vuetify-module
  */
  vuetify: {
    customVariables: ['~/assets/variables.scss'],
    optionsPath: './vuetify.options.js',
    treeShake: true
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  }
}

```

**Comment by kevinmarrec** [comment]
@robsontenorio Shouldn't be `frameworkOptions` in `vuetify.options.js` but directly the object.

**Comment by robsontenorio** [comment]
Just removed `frameworkOptions` but no lucky.  Just tried to point to new `2.0.0-alpha.2` release.

I am facing two issues:

- `optionsPath: './vuetify.options.js'` does not take any effect to theme.
- hot reloading not working when changing it.

Am i missing any special config on my `nuxt.config.js` ?

**Comment by kevinmarrec** [comment]
@robsontenorio Could you provide a repository with the last changes so I can take a look and help you fix it ?

**Comment by clixmat** [comment]
Hi, I managed to fix it after reading the vuetify documentation, here.
https://vuetifyjs.com/en/customization/presets#default-preset

I leave an example of how the configuration should be.

Greetings.

![image](https://user-images.githubusercontent.com/41817274/72324616-5bf5ce80-3679-11ea-923f-a5697661b98d.png)

**Comment by robsontenorio** [comment]
@kevinmarrec here is https://github.com/robsontenorio/nuxt-vuetify2

@clixmat I am not using typescript.

**Comment by kevinmarrec** [comment]
@robsontenorio Well you're defining `themes.light` but `dark: true` makes your app use `dark` theme by default. You should first either removing `dark: true` or switch `themes.light` by `themes.dark`.

Then, if you use `2.0.0-alpha.x`, you should change `optionsPath` by `frameworkOptions`, as well as `treeShake` option which is not existing anymore.

```js
vuetify: {
    customVariables: ['~/assets/variables.scss'],
    frameworkOptions: './vuetify.options.js'
  }
```

![image](https://user-images.githubusercontent.com/25272043/72435772-2ea34080-379f-11ea-999a-faa2e1e67c69.png)

**Comment by robsontenorio** [comment]
@kevinmarrec Just worked! Thanks for your helping!

That information about `frameworkOptions ` shouldn't be in README?

**Comment by kevinmarrec** [comment]
@robsontenorio 
> The documentation of 2.0.0-alpha.x has not being updated yet.
