### ISSUE TITLE
Make fibers an optional dependency

### ISSUE THREAD

**Issue by fagerbur** [nuxt-community/vuetify-module#254]
**Is your feature request related to a problem? Please describe.**
Behind an enterprise proxy there are certificate validation issues with node-gyp which is required to use fibers.

**Describe the solution you'd like**
fibers isn't always needed and making it an optional dependency would prevent npm install from failing because it would remove the requirement for node-gyp and python and unneeded configuration time for something that isn't used.

**Describe alternatives you've considered**
There are quite a few hacky workarounds allowing unauthorized connections for node-gyp and they've implemented some options but that none of them are either a feasible or secure solution.

**Comment by kevinmarrec** [comment]
`fibers` is optional on `next` channel : https://github.com/nuxt-community/vuetify-module/blob/next/package.json#L40

**Comment by fagerbur** [comment]
Awesome, glad to see it's already been taken care of, thanks!
