### ISSUE TITLE
Issue with Vuetify when running nuxt.server.RenderRoute

### ISSUE THREAD

**Issue by t1mwillis** [nuxt-community/vuetify-module#255]
**Module version**
1.9.1

**Describe the bug**
When running integration tests using the example provided on the [Nuxt.js site](https://nuxtjs.org/examples/testing), I get an error in the console:

```
console.error node_modules/fibers/fibers.js:17
    ## There is an issue with `node-fibers` ##
    `/Users/.../testing/node_modules/fibers/bin/darwin-x64-72/fibers.node` is missing.
```

And the tests fail. Would love to have a method of integration testing routes.
Is there something missing from config in my build?

**To Reproduce**

- Clone repo: https://github.com/t1mwillis/Nuxt-Vuetify-Sample
- Run `npm i` within directory
- Run `npm test` to run tests, note failure on routes.spec.js
  - Run `npm test routes` to just test routes.spec.js

**Expected behavior**
Tests pass

**Screenshots**
Happy to add console screenshots, but for now I hope this context helps!

**Additional context**
The `node-fibers` module throws an error when running the tests and says `Try running this to fix the issue: /usr/local/Cellar/node/12.7.0/bin/node /Users/.../testing/node_modules/fibers/build`. After that, requests the following:
```
`darwin-x64-72` exists; testing
Problem with the binary; manual build incoming
node-gyp not found! Please ensure node-gyp is in your PATH--
Try running: `sudo npm install -g node-gyp`
spawn node-gyp ENOENT
```

Only other thing I'll say is thank you for your work on this module!

**Comment by t1mwillis** [comment]
After spending a few hours on this today, I deduced that we need to let `jest` know about `.node` files so I added `'node'` to the `moduleFileExtensions` array in `jest.config.js` file.

`moduleFileExtensions: ['js', 'vue', 'json', 'node'],`

At this point, I am still having trouble running these tests and am curious if I'm simply trying to do something impossible, i.e. run E2E tests using Nuxt/Vuetify/Jest.

**Comment by kevinmarrec** [comment]
@t1mwillis Could you try with `2.0.0-alpha.x` version, which has optional `fibers` and may fix your issue ? You'll need to read https://github.com/nuxt-community/vuetify-module/pull/177 for breaking changes.

**Comment by t1mwillis** [comment]
@kevinmarrec thanks for your response. I gave `2.0.0-alpha.3` a shot, but I get the same error. Ultimately we decided to move to Cypress for E2E tests and we are not seeing this issue.

I'll keep this up to date if we find any new information, but for now I think we can safely close this.

**Comment by VRuzhentsov** [comment]
I have success to build with this versions
```json
{
  "devDependencies": {
    "fibers": "^4.0.2",
    "sass": "^1.25.0",
    "sass-loader": "^7.2.0"
  }
}
```

took from https://www.npmjs.com/package/sass-loader

readme
