### ISSUE TITLE
Translate option is not working

### ISSUE THREAD

**Issue by brolnickij** [nuxt-community/vuetify-module#26]
Hello.
In the nuxt.config.js i plug in the translation file.
`const VUETIFY_RU_I18N = require('vuetify/src/locale/ru.ts')`

And in the plugin module settings I do the following settings:
```js
vuetify: {
  treeShake: true,
  lang: {
    locales: { VUETIFY_RU_I18N }, // or locale: { VUETIFY_RU_I18N }
    current: 'ru'
  }
},
```

I also tried such settings:
```js
vuetify: {
  treeShake: true,
  lang: {
    locales: VUETIFY_RU_I18N, // or locale: VUETIFY_RU_I18N
    current: 'ru'
  }
}
```

It all doesn't work. What could be the problem? Thank!

**Comment by Dream5561** [comment]
It works for me in this way
`const RU_I18N= require('vuetify/src/locale/ru.ts')`
```
  vuetify: {
    treeShake: true,
    lang: {
      locales: {
        ru: RU_I18N
      },
      current: 'ru'
    },
```

**Comment by brolnickij** [comment]
> It works for me in this way
> `const RU_I18N= require('vuetify/src/locale/ru.ts')`
> 
> ```
>   vuetify: {
>     treeShake: true,
>     lang: {
>       locales: {
>         ru: RU_I18N
>       },
>       current: 'ru'
>     },
> ```

Hello! For some reason it does not work for me..

**Comment by brolnickij** [comment]
For those who face the same problem:
`const VUETIFY_RU_I18N = require('vuetify/es5/locale/ru')`
```js
vuetify: {
  treeShake: true,
  lang: {
    locales: {
      ru: VUETIFY_RU_I18N.default
    },
    current: 'ru'
  }
}
```
Pay attention to: `VUETIFY_RU_I18N.default`
