### ISSUE TITLE
All children of v-img component are hidden

### ISSUE THREAD

**Issue by mryassera** [nuxt-community/vuetify-module#262]
**Module version**
`@nuxtjs/vuetify@1.10.1` and `@nuxtjs/vuetify@1.9.1`

**Describe the bug**
```
<v-img :aspect-ratio="16/9" src="https://cdn.vuetifyjs.com/images/parallax/material.jpg">
  <v-row align="end" class="lightbox white--text pa-2 fill-height">
    <v-col>
      <div class="subheading">Jonathan Lee</div>
      <div class="body-1">heyfromjonathan@gmail.com</div>
    </v-col>
  </v-row>
</v-img>
```
The name and email is hidden.
After "inspect element" the image is over texts and not the background

Is working with `@nuxtjs/vuetify@1.0.0` I updated to `1.9.1` then `1.10.1` then appeared the problem 

**Screenshots**
![Annotation 2020-01-16 045937](https://user-images.githubusercontent.com/45864194/72486919-64870a00-381d-11ea-8acb-8b56842dc46e.jpg)
![Annotation 2020-01-16 050530](https://user-images.githubusercontent.com/45864194/72487285-99e02780-381e-11ea-8ed7-056a4bd88af2.jpg)

**Comment by kevinmarrec** [comment]
@mryassera Sounds like a Vuetify behavior change, could you compare Vuetify version in both cases with either `yarn why vuetify` or `npm ls vuetify`  ?

**Comment by mryassera** [comment]
I found the solution.
I converted old version, also still hidden!, After I converted parent of v-img (v-card) to ltr then working
The issue is not with version, is with `direction: rtl` 

Thank you @kevinmarrec
