### ISSUE TITLE
Errors with nuxt generate when using latest v1.10.2 of module

### ISSUE THREAD

**Issue by manastalukdar** [nuxt-community/vuetify-module#268]
**Module version**
1.10.2

**Describe the bug**
With the latest version of the module, `nuxt generate` results in `TypeError: Cannot assign to read only property 'base' of object '#<Object>'`.

**To Reproduce**
https://github.com/manastalukdar/manastalukdar.github.io/tree/issue89

1. Get _blog_metadata.json_ file from [here](https://github.com/manastalukdar/manastalukdar.github.io/files/4084857/blog_metadata.zip).
2. Under the `website/static` folder, create a new folder called `blogdata`.
3. Under `blogdata` folder create a new folder called `metadata` and copy the _blog_metadata.json_ from step 1 into this new `website/static/blogdata/metadata` folder.
4. Copy the folder (along with all sub-folders) `website/blog/2019` into `website/static/blogdata`. `website/static/blogdata` should now have 2 subfolders: `2019` and `metadata`.
5. Run `npm install`.
6. Run `npm run generate`.

**Expected behavior**
All pages get generated correctly.

**Actual Behavior**

```
TypeError: Cannot assign to read only property 'base' of object '#<Object>'
    at W (server.js:1:7914)
    at W (server.js:1:7898)
    at W (server.js:1:7898)
    at W (server.js:1:7898)
    at W (server.js:1:7898)
    at new We (server.js:1:749132)
    at Wo.use (server.js:1:768689)
    at new Wo (server.js:1:768382)
    at Go (server.js:1:770226)
    at hi (server.js:1:774607)
    at async e.default (server.js:1:775704)
```

**Comment by dwfee** [comment]
I experienced same error, when using custom names for colors, when you stick with the default names, primary, secondary etc. I will work, this is, I think not a generate issue, but a general issue. Please try it, to confirm my idea.
Greetings from dwfee, Bavaria

**Comment by manastalukdar** [comment]
@dwfee You are correct. I have verified that the custom color names are causing the problem.

**Comment by douira** [comment]
I'm getting the same error when running it normally with ´nuxt dev` but for some reason this is also happening on the older module version `1.9.2` now. Maybe it's some kind of cache issue? This error only pops up after reloading the page or navigating with some kind of new load. (not just a SPA navigation)

**Comment by douira** [comment]
I can confirm this same error still happens on the 1.11.0 version of this module.

**Comment by dschreij** [comment]
I experienced the same problem. I noticed that if I set all config option in `nuxt.config.js` everything works correct, but once I place the vuetify settings in an external .js file using the `optionsPath` config option, then this error starts to occur.

**Comment by 1isten** [comment]
Same here, cannot use `optionsPath` option to refer to my external config file..

**Comment by kevinmarrec** [comment]
Hi everyone,

I's cause :

```js
{
  primary: colors.red
}
```
it not valid.

You need to use :

```js
{
  primary: colors.red.base
}
```

**Comment by kevinmarrec** [comment]
See : https://github.com/nuxt-community/vuetify-module/blob/master/test/fixture/vuetify.options.ts#L9

**Comment by dschreij** [comment]
I think I tried this, but it didn't work, but maybe I did it wrong, so for the base colors you can do
```
{
  primary: colors.red.base
}
```
but what about the colors with modifiers?
Is it
```
{
  primary: colors.red.lighten1.base
}
```
or simply
```
{
  primary: colors.red.lighten1
}
```
