### ISSUE TITLE
v1.0.0-beta.0 theme options themeCache & minifyTheme do not work

### ISSUE THREAD

**Issue by csheppard** [nuxt-community/vuetify-module#27]
Repo: https://github.com/csheppard/nuxt-vuetify-2/tree/vuetify-module

Specifying `themeCache` results in a server error:
```
TypeError
options.themeCache.get is not a function
```

`minifyTheme` also does not seem to work, the generated theme CSS still has whitespace.

**Comment by kevinmarrec** [comment]
@csheppard Looks like a Vuetify issue, is it still reproducible with our last beta version of the module ?

**Comment by ricardogobbosouza** [comment]
@csheppard you need to use a plugin for this
```js
// plugins/vuetify-theme-cache.js
import LRU from 'lru-cache'

const themeCache = new LRU({
  max: 10,
  maxAge: 1000 * 60 * 60 // 1 hour
})

export default (ctx) => {
  ctx.app.vuetify.framework.theme.options.themeCache = themeCache
}
```

```js
// nuxt.config.js
modules: [
  '@nuxtjs/vuetify'
],

plugins: [
  '~/plugins/vuetify-theme-cache.js'
]
```

**Comment by kevinmarrec** [comment]
Good catch @ricardogobbosouza , this is needed cause of some serialization of options I guess ?

**Comment by ricardogobbosouza** [comment]
@kevinmarrec yes, because of the serialization

**Comment by kevinmarrec** [comment]
@csheppard

With next module release version (1.0.0) you'll be able to use @ricardogobbosouza snippet and replace `ctx.app.vuetify.framework` by `ctx.$vuetify` as shorten path.

```js
export default (ctx) => {
  ctx.$vuetify.theme.options.themeCache = themeCache
}
```

**Comment by csheppard** [comment]
Great work, the plugin method is definitely needed as I had to stop using this module and go manual again as editing nuxt.config.js (adding icons/colour edits) requires full rebuild everytime.

**Comment by ricardogobbosouza** [comment]
@kevinmarrec can closed?

**Comment by kevinmarrec** [comment]
@csheppard Indeed it needs full rebuild when updating module options, we may implement a feature like providing a path (`string`) to the Vuetify options so it registers & watch it like a `plugin` to prevent these rebuilds.

**Comment by ricardogobbosouza** [comment]
@kevinmarrec maybe we should reopen this with this option you mentioned above

**Comment by kevinmarrec** [comment]
@ricardogobbosouza I would say new issue tagged as feature request

**Comment by kevinmarrec** [comment]
@ricardogobbosouza Created https://github.com/nuxt-community/vuetify-module/issues/77
