### ISSUE TITLE
Give support to Preset

### ISSUE THREAD

**Issue by reilue** [nuxt-community/vuetify-module#275]
**Is your feature request related to a problem? Please describe.**
Due a new option from [Presets](https://vuetifyjs.com/en/customization/presets)

**Describe the solution you'd like**
Add support to this feature, similar to breakpoint, icons, i8n & RTL.

**Describe alternatives you've considered**
If there is an example to set this Preset as a Nuxt Plugin, that would help. While we develop the feature for this module.

**Comment by reilue** [comment]
I figure out, that i need to read more carefully the doc. It actually works. Just stick to documentation.

**Comment by bensladden** [comment]
Are you able to give an example? ive tried this [https://codesandbox.io/s/nuxtjs-vuetify-kynn1](https://codesandbox.io/s/nuxtjs-vuetify-kynn1) but no joy

**Comment by reilue** [comment]
My way to do it.

1. Install the Vuetify Nuxt module

2. Install the preset

```
yarn add -D vue-cli-plugin-vuetify-preset-rally
```

3. Create a file in plugin/vuetifiy.js
```
import { preset } from 'vue-cli-plugin-vuetify-preset-rally/preset'

export default {
    ...preset
}
```
4. In nuxt.config.js set this:

```
vuetify: {
  customVariables: ['~/assets/variables.scss'],
  optionsPath: './plugins/vuetify.js'
}
```

And voila. Cheers!

**Comment by bensladden** [comment]
does not work for me unfortunately

**Comment by reilue** [comment]
You're right, it only load theme colors, but not the variables. :/

**Comment by reilue** [comment]
@bensladden I update the answer, hope this helps to others.

**Comment by seanaye** [comment]
@reilue I have followed your instructions and am still unable to correctly load the presets. The variables are not importing correctly from the sass-file. Some style from the preset is loaded like the 'primary' colour, but none of the style from the sass import loads.
