### ISSUE TITLE
How to use both Material Designs Icons and Font Awesome 5 together?

### ISSUE THREAD

**Issue by geoffreylzf** [nuxt-community/vuetify-module#280]
I expect the configuration should be something like this
```
export default {
  vuetify: {
    defaultAssets: {
        icons: ['mdi', 'fa']
    }
  }
}
```
but is does not work

**Comment by kevinmarrec** [comment]
Sorry but it out of scope of this feature as Vuetify itself doesn't provide such support unfortunately (https://vuetifyjs.com/en/customization/icons), you can try to ask on their repository directly to have solutions :)
