### ISSUE TITLE
nuxt-i18n and context access

### ISSUE THREAD

**Issue by Akhail** [nuxt-community/vuetify-module#29]
How can i use this module with the nuxt i18n if i need access to context (app, store)

**Comment by aldarund** [comment]
Not quite understand how its has anything to do with vuetify module.
If you have question please come to discord -> https://discord.gg/nHzfFwe
Github is for issues.

**Comment by Akhail** [comment]
That I need override the "t"property in vuetify https://vuetifyjs.com/en/framework/internationalization#vue-i18n passing a function that use app.i18n.t but I need have access to context is a feature request

**Comment by SasanFarrokh** [comment]
I'm overriding `t` function to use $i18n, How can i access a vue instance to access to $i18n?
Using it this way currently:
```
vuetify: {
    rtl: true,
    customVariables: ['~/assets/styles/variables.scss'],
    treeShake: true,
    lang: {
      locales: { fa, en },
      t (key, ...params) {
        return window.$nuxt.$i18n.t(key, params)
      },
      current: 'fa'
    },
    theme: {
      themes: {
        light: {
          primary: '#fb8c00',
          secondary: '#b0bec5',
          accent: '#7C4DFF',
          error: '#b71c1c'
        }
      }
    }
  }
```

**Comment by kevinmarrec** [comment]
@Akhail @SasanFarrokh 

Indeed it's more likely around a feature request, to be able to access Nuxt context around Vuetify options. I just created https://github.com/nuxt-community/vuetify-module/issues/97, you can comment on it or add thumbsup if that's what you would be looking for.
