### ISSUE TITLE
Icon's cdn is loaded even install icon-font locally

### ISSUE THREAD

**Issue by amotarao** [nuxt-community/vuetify-module#294]
**Module version**
v1.11.0

**Describe the bug**
Icon's cdn is loaded even install icon-font locally.

**To Reproduce**

1. Install @mdi/font
1. Add `import '@mdi/font/css/materialdesignicons.css' `
1. See `<link href="stylesheet" src="icon-cdn">` in `<head>`

**Expected behavior**
Icon's cdn is NOT load.

**Screenshots**
None

**Additional context**
None

**Comment by Geowan** [comment]
You need to set   defaultAssets to false in the vuetify configuration. 
          vuetify: {
            defaultAssets:false,

              //other config options
         },

see [This reference](https://github.com/nuxt-community/vuetify-module/issues/108)

**Comment by Geowan** [comment]
Duplicate of #108

**Comment by amotarao** [comment]
I see.
Thank you for teaching.
