### ISSUE TITLE
Phone keyboard does not work with text field

### ISSUE THREAD

**Issue by simeon9696** [nuxt-community/vuetify-module#320]
**Module version**
v1.11.2

**Describe the bug**
If I enter text into the field on desktop it's fine. Even viewing the browser through Chrome DevTools and using the PC keyboard works. But direct entry using the phone's keyboard does not. The text just gets overlayed on the label.

![image](https://user-images.githubusercontent.com/31748055/80853075-c9634600-8bfb-11ea-9852-e782f53cd707.png)

What's more interesting is that it focuses properly if you type a space or punctuation and then the letters.

![image](https://user-images.githubusercontent.com/31748055/80853080-d122ea80-8bfb-11ea-9bdf-668750de1986.png)

And yes, that's all the code I have in the file haven't even added in export defaults yet

**To Reproduce**
```
<template>
    <v-container>
        <v-row>
            <v-col cols='12'>
                <v-text-field
                    label="This is a label"
                    single-line
                    solo
                ></v-text-field>
            </v-col>
        </v-row>
    </v-container>
</template>
```
Start a new file and enter the above code. Then launch nuxt with this in nuxt.config.js
```
  server: {     
    port: 8000, // default: 3000     
    host: '0.0.0.0', // default: localhost   
  }, 
```
So you can connect to it on a mobile browser by entering the generated IP when you run npm run dev.  Then try to enter text using the mobile keyboard

**Expected behavior**
The label disappears and the text is not overlayed

**Comment by simeon9696** [comment]
So far this seems to be an issue with Gboard, try updating your mobile keyboard (haven't personally tested that but there have been anecdotal reports)

**Comment by sugoidesune** [comment]
You should post this to the vuetify repo.
This repo simply installs it in nuxt.
https://github.com/vuetifyjs/vuetify/issues
