### ISSUE TITLE
[Vuetify] Multiple instances of Vue detected

### ISSUE THREAD

**Issue by dylan-moore** [nuxt-community/vuetify-module#322]
**Module version**
1.11.2

**Describe the bug**
Vuetify says that there are multiple instances and the page does not display.

**To Reproduce**

This is my nuxt config.
https://gist.github.com/dylan-moore/fd4b22a143fe82ceda830f61444f2a62

**Expected behavior**
My content should display.

**Screenshots**
<img width="736" alt="Screenshot 2020-05-05 at 12 59 48" src="https://user-images.githubusercontent.com/60218243/81063740-50504100-8ed0-11ea-8052-665244cbd952.png">

**Additional context**
The SSR content is correct but when the javascript loads in it breaks.

I have tried everything I could think of including just using vuetify as a plugin in nuxt. I am out of ideas.

**Comment by aonghas** [comment]
What did you end up doing? I have the same issue.

**Comment by dylan-moore** [comment]
> What did you end up doing? I have the same issue.

I haven't worked out anything unfortunately. I think this may be an issue with Nuxt or Vuetify themselves since I tried to just use Vuetify as a plugin and it still didn't work.

**Comment by cmoeser** [comment]
Same issue

**Comment by dylan-moore** [comment]
Well after three months of banging my head against the wall and pulling almost all of my hair out I think I may have fixed it.

I extended my webpack config inside my nuxt config like so and It seems to work fine.

    extend(config, ctx) {

        // Fix multiple instances of vue.

        config.resolve.alias.vue$ = path.resolve(

            __dirname, './node_modules/vue/dist/vue.esm.js'

        )
    }

**Comment by henrygrant** [comment]
> Well after three months of banging my head against the wall and pulling almost all of my hair out I think I may have fixed it.
> 
> I extended my webpack config inside my nuxt config like so and It seems to work fine.
> 
> ```
> extend(config, ctx) {
> 
>     // Fix multiple instances of vue.
> 
>     config.resolve.alias.vue$ = path.resolve(
> 
>         __dirname, './node_modules/vue/dist/vue.esm.js'
> 
>     )
> }
> ```

I could kiss you. Thanks!
