### ISSUE TITLE
Setting Vuetify Theme On Server Side

### ISSUE THREAD

**Issue by big213** [nuxt-community/vuetify-module#326]
I have been trying to figure out a solution to this problem for a while on the nuxt/vuetify starter app, and I haven't been able to get it to work. Let's say the website stores the theme preferences (dark vs light) in localStorage on the client side (for example, if you want to save the user's theme preferences. How can we get the app to read this preference and render accordingly?

My current solution:

/layouts/default.vue
```
...
  mounted() {
    if(process.client) {
      this.$vuetify.theme.dark = localStorage.getItem("theme") != "light";
    }
  },
...
```

nuxt.config.js
```
  vuetify: {
    customVariables: ['~/assets/variables.scss'],
    theme: {
      dark: true,
      themes: {
        dark: {
          primary: colors.blue.darken2,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        },
        light: {
          primary: colors.blue.lighten2,
          accent: colors.grey.lighten3,
          secondary: colors.amber.lighten3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        }
      },
    }
  },
```

Problems:
- The site loads in the dark theme, and then is suddenly toggled to light theme on mounted (when the localStorage variable is set to light), but this is quite a big color change. Ideally, it would be able to load as light or dark and not have to switch suddenly.
- Using this method, the light theme css is not properly generated. The background of the entire website is light, but the "primary/accent/secondary" css colors are still on the dark theme. This is very strange because if I toggle `this.$vuetify.theme.dark = !this.$vuetify.theme.dark` using some button, it does render the light theme properly, but when I do the toggle on `mounted()` it does not.

Is there some way to handle this? Maybe I'm missing something entirely...

**Comment by big213** [comment]
Got the light theme css to be generated properly by doing this:

plugins/vuetify.js
```
export default (context) => {
  if(process.client) {
    context.$vuetify.theme.dark = localStorage.getItem("theme") != "light";
  }
}
```

Still not exactly what I wanted since the page still loads in dark theme by default, and then will switch to light theme if necessary. If anyone comes up with a solution for that, please do share!

**Comment by helderhernandez** [comment]
> Got the light theme css to be generated properly by doing this:
> 
> plugins/vuetify.js
> 
> ```
> export default (context) => {
>   if(process.client) {
>     context.$vuetify.theme.dark = localStorage.getItem("theme") != "light";
>   }
> }
> ```
> 
> Still not exactly what I wanted since the page still loads in dark theme by default, and then will switch to light theme if necessary. If anyone comes up with a solution for that, please do share!

Muchas gracias por sus ideas, logre implementar su solución acompañando un plugin y un middleware, ver el siguiente enlace https://github.com/nuxt-community/vuetify-module/issues/327#issuecomment-1216926846
