### ISSUE TITLE
Error: Module `@nuxtjs/vuetify` not found. (v2.0.0-beta.2)

### ISSUE THREAD

**Issue by samyrooster** [nuxt-community/vuetify-module#338]
Because of fibers error on cPanel/CentOS/Cloudlinux servers, I use v2.0.0-beta.2

But npm returns error on build or dev running.

No problem with v1.11.2, but the alpha and beta versions have error.

```
✖ Nuxt Fatal Error
Error: Module `@nuxtjs/vuetify` not found. Please ensure `@nuxtjs/vuetify` is in `devDependencies` and
installed. HINT: During build step, for npm/yarn, `NODE_ENV=production` or `--production` should NOT be
used.
```
![2020-06-04_163704](https://user-images.githubusercontent.com/20831792/83755158-5f1e4500-a682-11ea-8f19-1c8317cc129b.jpg)

**Comment by samyrooster** [comment]
I deleted the node_modules folder and re runned npm install and problem solved.

**Comment by UditNarayan31** [comment]
@samyrooster its a common answer, i am seeing everywhere. and its not working

**Comment by TarasKryvko** [comment]
> @samyrooster its a common answer, i am seeing everywhere. and its not working

Have you found an answer?

**Comment by markdiverta** [comment]
Try run `npm install @nuxtjs/vuetify -D` to install Vuetify component, and it should fix the problem.

**Comment by wriozumi** [comment]
@samyrooster  how did you solve the problem?
