### ISSUE TITLE
v0.5.6 vs 1.0.0-beta.3 with `~` path alias

### ISSUE THREAD

**Issue by bluelovers** [nuxt-community/vuetify-module#34]
repo
https://github.com/bluelovers/test-nuxt-app

if use v0.5.6, build will done

but if use 1.0.0-beta.3 , build will show error

> ENOENT: no such file or directory, open `pages\_test\plugin\markdownit\~\assets\_test\plugin\markdownit\hello.md`

**Comment by kevinmarrec** [comment]
@bluelovers Is it still outputing errors with last version of beta ?

**Comment by ricardogobbosouza** [comment]
@kevinmarrec 
I could not reproduce

**Comment by kevinmarrec** [comment]
@ricardogobbosouza Even if it could be reproducible, such error couldn't be Vuetify related 🤔
It's something to do with path aliasing so more likely webpack aliases.

Should we close this ? If there is really an issue regarding aliases it should probably be opened around Nuxt repo

**Comment by ricardogobbosouza** [comment]
@kevinmarrec i agree
I think you can close

**Comment by kevinmarrec** [comment]
Closing, @bluelovers please open issue on Nuxt repo if you still have aliases issue.
