### ISSUE TITLE
got Maximum call stack size exceeded when using server side datatable

### ISSUE THREAD

**Issue by handhikadj** [nuxt-community/vuetify-module#353]
**Module version**
1.11.2

**Describe the bug**
as the title said

**To Reproduce**
https://codesandbox.io/s/dazzling-wildflower-zywy4

1. just click the link, you will see the error right away

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/22522638/87135101-cc497980-c2c3-11ea-8210-45cf9e77b074.png)

**Comment by redzjovi** [comment]
The issue is not related with vuetify.

https://codesandbox.io/s/agitated-driscoll-5jqof?file=/pages/index.vue:2166-2222

Line 87, it should be string instead array.
`_sort: this.dataTable.paginationOptions.sortBy.join(",")`

**Comment by handhikadj** [comment]
it can't be a string. tried it and got `this.options.sortBy.findIndex is not a function`
anyway you can fork it and solve it

**Comment by redzjovi** [comment]
The vuetify datatable options.sortBy should be array, your dataTable.paginationOptions.sortBy is array. This is correct.

In your axios params._sort iss array, it's should be string.

The code already forked.

And also please check the official example https://vuetifyjs.com/en/components/data-tables/#paginate-and-sort-server-side.

**Comment by handhikadj** [comment]
would you show me your (forked) version

**Comment by handhikadj** [comment]
solved. sandbox is updated
