### ISSUE TITLE
I got a grey theme

### ISSUE THREAD

**Issue by HulioEglesias** [nuxt-community/vuetify-module#368]
Module versions:
    "@nuxtjs/vuetify": "^1.11.2",
    "vuetify": "^2.3.8"

**Describe the bug**
I got a grey theme as default(looks like a disabled but it is not) and cant change it
![image](https://user-images.githubusercontent.com/15662060/89706980-dd99aa80-d983-11ea-91e9-d1b058d8e358.png)

**To Reproduce**
```
<div class="editorInput">
        <v-text-field
          v-model="textVal"
          label="первое поле"
        />
      </div>
      <div class="editorInput">
        <v-checkbox
          v-model="checkboxVal"
          label="Checkbox 1"
        ></v-checkbox>
      </div>
      <div class="editorInput">
        <v-radio-group v-model="radioVal">
          <v-radio
            v-for="n in 3"
            :key="n"
            :label="`Radio ${n}`"
            :value="n"
          ></v-radio>
        </v-radio-group>
      </div>
      <div class="editorInput">
        <v-switch v-model="switch1" :label="`Switch 1: ${switch1.toString()}`"></v-switch>
      </div>
```

Why that happen and how can I fix it?

**Comment by Adamkillander96** [comment]
Do you have the `<v-app>` in the layout? No colors will be applied if it is not there.

**Comment by HulioEglesias** [comment]
> Do you have the `<v-app>` in the layout? No colors will be applied if it is not there.

Thanks, it helped!
