### ISSUE TITLE
Load correctly css when changing the `iconfont`

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt-community/vuetify-module#37]
Properly load CSS for each font type:

```js
// nuxt.config.js
{
  vuetify: {
    defaultAssets: {
      icons: {
        iconfont: 'md' // 'mdi' || 'md' || 'fa' || 'fa4'
      }
    }
  }
}
```

`mdi` => `https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css`
`md` => `https://fonts.googleapis.com/css?family=Material+Icons`
`fa` => `https://use.fontawesome.com/releases/v5.0.13/css/all.css`
`fa4` => `https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css`

**Comment by smajl** [comment]
+ solution for FA5 SVG, please

**Comment by kevinmarrec** [comment]
@ricardogobbosouza We would need to be aware of version upgrades of Font Awesome (but it's already the case for MDI icons)

**Comment by ricardogobbosouza** [comment]
@kevinmarrec  we can always use the latest version not?
https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@latest/css/all.min.css

**Comment by ricardogobbosouza** [comment]
@smajl use plugin for FA5 SVG 

```js
// plugins/vuetify-fa5-svg.js
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { fas } from '@fortawesome/free-solid-svg-icons'

Vue.component('font-awesome-icon', FontAwesomeIcon) // Register component globally
library.add(fas) // Include needed icons
```

```js
// nuxt.config.js
plugins: [
  '~/plugins/vuetify-fa5-svg.js'
],

modules: [
   '@nuxtjs/vuetify'
],

vuetify: {
  defaultAssets: false,
  icons: {
    iconfont: 'faSvg'
  }
}
```

**Comment by kevinmarrec** [comment]
@ricardogobbosouza Yes can use the latest versions if they indeed have a latest link

**Comment by ricardogobbosouza** [comment]
@kevinmarrec we should also have an option to `import` it into the plugin or inject it into the `head` as it is done today.

**Comment by blowsie** [comment]
How can we utilise faSvg to use other pro icons, such as the `light` variant ?
