### ISSUE TITLE
Deploying to Firebase Hosting

### ISSUE THREAD

**Issue by jomskidoodle** [nuxt-community/vuetify-module#371]
**Module version**
The version of the module you're using.

**Describe the bug**
I'm getting this error on my NuxtJS and Vuetify.
The import code was inserted after I create nuxtJS via CLI 
**npx create-nuxt-app <project-name>**

Firebase Deployment -> firebase deploy 

**Screenshots**
https://prnt.sc/tz3fv9

**Additional context**

**Comment by francoisauclair911** [comment]
Try 
`const colors = require(YOUR-PATH)`

**Comment by AustinDavies** [comment]
If you have your npm libs install on the Firebase hosting server then be aware that ALL npm libs listed under the devModules section will be ignored during installation; this includes the @nuxtjs/vuetify.

This is at least how I remembered it when dealing with Firebase & NuxtJS.
