### ISSUE TITLE
How I can hide “vuetify-theme-stylesheet” to CSS file instead of displaying in `<head>` tag.

### ISSUE THREAD

**Issue by love-xu** [nuxt-community/vuetify-module#385]
**Module version**
```
"dependencies": {
    "@nuxt/typescript-runtime": "^2.0.0",
    "nuxt": "^2.14.5",
    "@nuxtjs/axios": "^5.12.2"
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.5",
    "@nuxt/typescript-build": "^2.0.3",
    "@nuxtjs/vuetify": "^2.0.0-beta.2",
    "vuetify-dialog": "^2.0.10"
  }
```

**Describe the bug**
I was installed Nuxt via command `npx create-nuxt-app` with Vuetify plugin. 

Then I ran server via `npm run dev` or `npm run build` && `npm start ` and in page source I see CSS styles of Vuetify in `<head>` tag. 

After some googleing I found advice add `extractCSS: true`, in build section of `nuxt.config.js`. 

After that when I run `npm run build` && `npm start` css files are generating and linking to pages, 
but I still see some CSS styling (~500 lines) in `<style data-n-head="vuetify" type="text/css" id="vuetify-theme-stylesheet" nonce="undefined">`. 

How I can hide them to CSS file instead of displaying in `<head>` tag.

nuxt.config.js:
```
  /*
  ** Build configuration
  ** See https://nuxtjs.org/api/configuration-build/
  */
  build: {
    extractCSS: true
  }
```

**To Reproduce**
- not have

- not have

**Expected behavior**
How I can hide them to CSS file instead of displaying in `<head>` tag.

**Screenshots**
- not have

**Additional context**
- not have

**Comment by yanivduke** [comment]
https://github.com/vuetifyjs/vuetify/pull/7443#issuecomment-508480537

**Comment by nvitaterna** [comment]
Would be great to have this go through the built-in extractCSS plugin for nuxt.

**Comment by mathe42** [comment]
As this css is generated at runtime and not on build-time this is not possible this easy.

**Comment by mathe42** [comment]
I have some ideas to fix that (maybe with only a small change in vuetify and the rest in nuxt code) and will look into it. But don't expect a solution in the next 3 weeks.

**Comment by nvitaterna** [comment]
For now I've just taken the generated css, put it into my custom css and disabled the theme generation. Obviously a hacky fix - and needs to be re-copied if you make changes to your theme variables.

**Comment by mathe42** [comment]
How did you disabled it?

**Comment by nvitaterna** [comment]
In nuxt.config.ts:

```js
...
vuetify:
  theme: {
    disable: true,
  },
},
...
```

**Comment by mathe42** [comment]
My idea was to disable the theme and use the original function I think https://github.com/vuetifyjs/vuetify/blob/c5556a5f3df0d4ce74f987dd5c683f46dd26f359/packages/vuetify/src/services/theme/utils.ts#L80 to generate it at build time.

**Comment by mathe42** [comment]
But we don't have the dark mode toggle than...

**Comment by love-xu** [comment]
> For now I've just taken the generated css, put it into my custom css and disabled the theme generation. Obviously a hacky fix - and needs to be re-copied if you make changes to your theme variables.

I did the same thing。

**Comment by love-xu** [comment]
Thank you for your attention. I will close this issue.

**Comment by farhodhojiev** [comment]
this is very strange, since out of 3 projects only one is so, and in others it is not.
Has anyone solved the problem?

**Comment by itelmenko** [comment]
So issue is not solved.
