### ISSUE TITLE
Use modules with typescript and eslint

### ISSUE THREAD

**Issue by yariksav** [nuxt-community/vuetify-module#4]
Hello guys!
Example, if I installed and use nuxtjs/vuetify. Vuetify has own index.d.ts file

Then in project typescript modules eslint will emphasizes with "error not found" all vuetify params, such as this.$vuetify.colors etc

This because all nuxt modules generate from string templates

Question: Is it possible to use some module in this package with typescript and eslint|tslint?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/modules/issues/c143">#c143</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
Hi @yariksav , I used Nuxt TypeScript + Vuetify in a little project with no problems, here is my `tsconfig.json`:

```json
{
  "extends": "@nuxt/typescript",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ]
    },
    "experimentalDecorators": true,
    "types": [
      "@types/node",
      "@nuxt/vue-app",
      "vuetify"
    ]
  }
}
```

You need the `vuetify` part to make it work I think.

*FYI I'm only using `tslint` and not `eslint` + `tslint`.*

**Comment by yariksav** [comment]
Thank you, @kevinmarrec, I will try it
