### ISSUE TITLE
bug in npm update with sass loader

### ISSUE THREAD

**Issue by YallaDealz** [nuxt-community/vuetify-module#412]
using --force Recommended protections disabled.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: node-sass@5.0.0
npm ERR! node_modules/node-sass
npm ERR!   node-sass@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional node-sass@"^4.0.0" from sass-loader@8.0.2
npm ERR! node_modules/sass-loader
npm ERR!   sass-loader@"^8.0.2" from the root project
npm ERR!   sass-loader@"^8.0.2" from @nuxtjs/vuetify@1.11.2
npm ERR!   node_modules/@nuxtjs/vuetify
npm ERR!     dev @nuxtjs/vuetify@"^1.11.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

**Comment by clarkdo** [comment]
Duplicate of https://mail.google.com/mail/u/0/#inbox/FMfcgxwKkbfsfLdzJgFRNHcTPWkSGwxG

**Comment by oanstein** [comment]
> https://mail.google.com/mail/u/0/#inbox/FMfcgxwKkbfsfLdzJgFRNHcTPWkSGwxG

Can't read a mail.google link. What issue are you referring to? I have the same problem.

**Comment by clarkdo** [comment]
Sorry, issue is https://github.com/nuxt/nuxt.js/issues/8655, issue has been fixed in latest vuetify-module v1.11.3
