### ISSUE TITLE
Nuxt build error "sass-loader"

### ISSUE THREAD

**Issue by Batuhanalperen** [nuxt-community/vuetify-module#416]
**Module version**
^1.11.3

**Describe the bug**
I get "Nuxt build error" when I run "npm run build". Everything working fine at development. It says it has something wrong with sass-loader.

**To Reproduce**

1. Go to terminal
2. Run "npm run build"
3. See error

**Expected behavior**
Successful build.

**Screenshots**
<img width="1424" alt="Screen Shot 2021-02-08 at 20 57 44" src="https://user-images.githubusercontent.com/40668308/107261753-bfa32480-6a50-11eb-8cc7-c43e4cb7cd55.png">

**Comment by larzon83** [comment]
Please show some code. Looks like you made a css class with the name „rgba(...)“ - which is wrong.

**Comment by Batuhanalperen** [comment]
I did not edit any scss files or variable related to vuetify. As I said, all is well on development mode.

**Comment by larzon83** [comment]
Do you have a repo to look into or codesandbox? Otherwise it’s not possible to help...
