### ISSUE TITLE
Please make current beta available

### ISSUE THREAD

**Issue by phifa** [nuxt-community/vuetify-module#43]
https://github.com/vuetifyjs/vuetify/releases
v2.0.0-beta.7.

Happy to help out, not sure how. Maybe just chaning the dep in package.json? 

```
  "dependencies": {
    ...
    "vuetify": "^2.0.0-beta.7",
    ...
  },
```

**Comment by akaHeimdall** [comment]
@phifa Looks like the beta dependency is in there now.
https://github.com/nuxt-community/vuetify-module/blob/next/package.json
