### ISSUE TITLE
Manual import causes compilation error on Nuxt 12.14.x

### ISSUE THREAD

**Issue by Kapcash** [nuxt-community/vuetify-module#430]
**Module version**
v.1.11.3

**Describe the bug**
When importing a component manually from the `nuxt.config.js` file, it causes a compilation error.

```javascript
import { VRow, VCol } from "vuetify/lib";
```

Then, running `yarn dev`, we get the error: 

```
 FATAL  Invalid or unexpected token                                                                                                                                                                   17:39:45

  @import '../../styles/styles.sass'
  ^
  
  SyntaxError: Invalid or unexpected token
  at Object.compileFunction (node:vm:356:18)
  at Generator.next (<anonymous>)
  at Object.<anonymous> (node_modules/vuetify/lib/components/VApp/VApp.js:1)
  at Generator.next (<anonymous>)
```

The goal is to register these components globally, but I found out not updating the `treeShake` option don't have any relation with the bug.

```javascript
    // Like this or with just `true`, the error is the same.
    treeShake: {
      components: [VRow, VCol],
    },
```

**To Reproduce**

[Codesandbox link](https://codesandbox.io/s/nuxtjs-vuetify-forked-to9l0?file=/nuxt.config.js)

1. Open `nuxt.config.js` file.
2. Run `yarn dev` on the codesandbox console.
3. See the error on the console.

If you remove the import line, the app starts without errors.

**Expected behavior**
Importing the components should not cause any issue.

**Additional context**
I reproduced using nuxt v.2.14.12 or under. Upgrading to v.2.15.3 fixes the problem.
Nonetheless, I expected it to work with this version of Nuxt.

**Comment by mathe42** [comment]
This option is not supportet...

You can add a Nuxt-Plugins that registers these components manualy:

```js
Vue.component('VCol', VCol)
```

and so on (Make shure to import the right stuff)

**Comment by Kapcash** [comment]
This is what I did as a workaround for the moment, yes :)

But what do you mean it is not supported? It's literally described on the documentation ([#treeshake](https://github.com/nuxt-community/vuetify-module#treeshake)). 

Also, as mentioned, even without updating the module's `treeshake` option, just importing the components causes the issue. And I'm not seeing why a simple import could break the vuetify compilation...

Do you have any idea for this?

**Comment by mathe42** [comment]
OK. Did not know about this feature... But you have to use strings and not import the components so:

```js
    treeShake: {
      components: ['VRow', 'VCol'],
    }
```

**Comment by Kapcash** [comment]
It worked, thank you! :)

I got confused because from [vuetify documentation](https://vuetifyjs.com/en/features/treeshaking/#manually-importing), you have to import the component.
