### ISSUE TITLE
Error sass-loader in VWindow.sass

### ISSUE THREAD

**Issue by NguyenThanh1995** [nuxt-community/vuetify-module#442]
Hi,

I use @nuxtjs/vuetify@1.11.3. 

When I run 

``` bash
yarn build
```

 it shows this error:
![image](https://user-images.githubusercontent.com/45375496/115708677-7ea58580-a39a-11eb-838d-e693f5a9860b.png)

Repo: https://github.com/NguyenThanh1995/sudoku-app

**Comment by larzon83** [comment]
This is an issue with dart-sass that has been fixed already. Easiest way to get the fix is to nuke your package-lock.json and node_modules folder and run `npm install`.

Or, in your package.json add this to devDependendies:
"sass": "1.32.11"

**Comment by NguyenThanh1995** [comment]
I tried both but the error keeps coming

**Comment by larzon83** [comment]
Ah, you're running on vercel. Maybe some vercel cache. Do a redeploy and uncheck the box "Include Build Cache". Also try running your build script locally.

**Comment by NguyenThanh1995** [comment]
I tried ``` bash yarn build ``` on my window 10 and it still doesn't work

**Comment by larzon83** [comment]
I checked out your repo. Deleted `node_modules` folder and `yarn.lock`file and then fired up `yarn` again. The build then succeeds with `yarn build`.

**Comment by NguyenThanh1995** [comment]
Ok. This method working me. Thanks
