### ISSUE TITLE
"/" as divide symbol deprecated in latest sass release - build errors

### ISSUE THREAD

**Issue by bbialas** [nuxt-community/vuetify-module#446]
**Module version**
1.11.3

**Describe the bug**
After installing latest version of this module, it downloaded as dependency latest version of SASS which is 1.33.0.
In this sass version, they introduced braking change and deprecated `/` as divider symbol in favour of `math.div()`.

Now during build, it throws errors like:
```
: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($grid-gutter, 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
63 │     'md': $grid-gutter / 3,
   │           ^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/styles/settings/_variables.scss 63:11  @import
    node_modules/vuetify/src/styles/settings/_index.sass 1:9        @import
    node_modules/vuetify/src/styles/styles.sass 2:9                 @import
    node_modules/vuetify/src/styles/elements/_code.sass 1:9         @import
    node_modules/vuetify/src/styles/elements/_index.sass 2:9        @import
    node_modules/vuetify/src/styles/main.sass 8:9                   root stylesheet
```
**To Reproduce**
Just install latest version of this module.

**Expected behavior**
Long term solution would be to replace `/` with `math.div()` in the whore repo.
Quick fix could be to change package.json and lock sass dependency to version **1.32.12**

**Comment by Calion54** [comment]
I get the same error with "@nuxtjs/vuetify": "1.11.2" and "nuxt": "2.15.6"

**Comment by Heniker** [comment]
If you use Yarn you can put
```js
"resolutions": {
  "@nuxtjs/vuetify/**/sass": "1.32.8"
},
```
in your package.json and it should work.

**Comment by a1xon** [comment]
Same Error with  "@nuxtjs/vuetify": "1.11.**3**" and "nuxt": "2.15.6"

**Comment by Tukizz** [comment]
i got same error here how to fix it? 
i use ```nuxt: 2.15.3``` ```@nuxtjs/vuetify: 1.11.3``` and nuxt typescript.

when i use ```treeShake: true``` it's get the error.
but if i not use ```treeShake``` it's working & not get error

**Comment by bbialas** [comment]
The temporary solution proposed by @Heniker works perfectly, thank you.

**package.json**
```
"resolutions": {
  "@nuxtjs/vuetify/**/sass": "1.32.12"
}
```

**Comment by erikeuserr** [comment]
@Heniker Is there a equivalent solution available for NPM users?

**Comment by erikeuserr** [comment]
For regular NPM users there is another solution available (as a temporary fix). 
- Install `npm-force-resolutions`. 
- Add  `"preinstall": "npx npm-force-resolutions"` to your npm scripts.
- Add below to `package.json`: 

``` 	
"resolutions": {
	"sass": "1.32.12"
}
```

**Comment by tabuz** [comment]
@erikeuserr In order this to work for me i had to use 
```
"resolutions": {
  "@nuxtjs/vuetify/**/sass": "1.32.12"
}
```

instead of what you suggest 
```
"resolutions": {
	"sass": "1.32.12"
}
```

But it works. Thank you!

**Comment by thomasvogelaar** [comment]
> If you use Yarn you can put
> 
> ```js
> "resolutions": {
>   "@nuxtjs/vuetify/**/sass": "1.32.12"
> },
> ```
> 
> in your package.json and it should work.

This doesn't seem to work in my monorepo project, unfortunately.

**Comment by krkaa** [comment]
I have the same error. is there a solution to this problem?

**Comment by Tukizz** [comment]
this my step to handle this error for now  

1. in your ```package.json``` add 
```json
"preinstall": "npx npm-force-resolutions"
 ```
inside the scripts section  

2. add
```json 
"resolutions": {
  "sass": "1.32.12"
},
```
above your scripts section 
 
3. after that run command ```npm i``` after finish run again your project and voila the error was gone

**Comment by rahulkumarsingh73690** [comment]
Same error

**Comment by SocketSomeone** [comment]
Same error

**Comment by rahulkumarsingh73690** [comment]
Solution for NPM users: 

`npm i sass@1.32.8`

No need to change anything but if you still face issue then `treeShake: false`

**Comment by Tobeyforce** [comment]
> Temporary solution for NPM users:
> 
> `npm i sass@1.32.8`
> 
> No need to change anything but if you still face issue then `treeShake: false`

This worked for me.

**Comment by rahulkumarsingh73690** [comment]
@clarkdo @Atinux @pi0 

Please fix this issue or provide a permanent solution :)

**Comment by xolott** [comment]
I'd tried to force Vuetify version `2.5.2` which [address this issue](https://github.com/vuetifyjs/vuetify/releases/tag/v2.5.2), adding to my package.json

```
"devDependencies": {
    ...
    "vuetify": "2.5.2",
    "sass": "1.34.0",
    "sass-loader": "10.2.0"
}
```

No luck. It outputs multiple `SassError: @use rules must be written before any other rules.`

```
ERROR in ./node_modules/vuetify/src/components/VBanner/VBanner.sass
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
4 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VBanner/VBanner.sass 4:1  root stylesheet
```

But the actual file contains nothing before `@use 'sass:math'`

```
1| // Imports
2| @use 'sass:math'
```

I assume that maybe there is some loader prepending something before the file content.

Using this solves the error but keeps the division warnings

```
{
    ...
    "vuetify": "2.4.2",
    "sass": "1.32.8"
}

**Comment by mostafaznv** [comment]
this worked for me:
```
"devDependencies": {
        "@nuxtjs/vuetify": "^1.11.3",
        "sass": "~1.32.13",
        "sass-loader": "^10.1.1"
}
```
