### ISSUE TITLE
New Sass Deprecation

### ISSUE THREAD

**Issue by Sardor01** [nuxt-community/vuetify-module#456]
@KaelWD yesterday locked sass version to ~1.32.13, PLEASE publish it to npm for that change to be applied;

Otherwise there is a big error

![image](https://user-images.githubusercontent.com/58367523/120646828-59c12980-c493-11eb-8567-942a0dd509f9.png)

**Comment by GGG-KILLER** [comment]
If you use `yarn`, you can use the [`resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) section in `packages.json` to restrict `sass` to 1.32.13 (as of this post, the version with the `~1.32.13` pin hasn't been pushed to NPM yet):
```json
  "resolutions": {
    "sass": "~1.32.13"
  }
```

**Comment by Sardor01** [comment]
> If you use `yarn`, you can use the [`resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) section in `packages.json` to restrict `sass` to 1.32.13 (as of this post, the version with the `~1.32.13` pin hasn't been pushed to NPM yet):
> 
> ```json
>   "resolutions": {
>     "sass": "~1.32.13"
>   }
> ```

Yep, that seems to be the solution to the problem
