### ISSUE TITLE
Using / for division is deprecated and will be removed in Dart sass 2.0.0

### ISSUE THREAD

**Issue by tarreislam** [nuxt-community/vuetify-module#457]
I did a critical mistake of doing `npm update` without checking all forums on the internet for bugs.

steps to reproduce

* 1. run `npm run dev`
* 2. Wait for build
* 3. Enjoy hackertyper on crack telling 

![Drag Racing](https://i.imgur.com/oXrB2qX.png)

**Comment by GGG-KILLER** [comment]
If you use `yarn`, you can use the [`resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) section in `packages.json` to restrict `sass` to 1.32.13 (as of this post, the version with the `~1.32.13` pin hasn't been pushed to NPM yet):
```json
  "resolutions": {
    "sass": "~1.32.13"
  }
```

**Comment by Sardor01** [comment]
#456

**Comment by tarreislam** [comment]
Thanks @GGG-KILLER
