### ISSUE TITLE
how use breakpoint with vuetify module

### ISSUE THREAD

**Issue by matamune94** [nuxt-community/vuetify-module#46]
my config:
```
  vuetify: {
    theme:{
      breakpoint: {
        thresholds: {
          xs: 340,
          sm: 540,
          md: 800,
          lg: 960,
          xl: 1280,
        }
      }
    },
	  treeShake: checkProduction()
  },
```
it not working , can you tell me the wrong place?

**Comment by mgreengithelps** [comment]
I think you need to move the breakpoint object up a level (out of the theme object):

```
vuetify: {
  breakpoint: {
     ...
  }
}
```

**Comment by matamune94** [comment]
> Tôi nghĩ bạn cần di chuyển đối tượng điểm dừng lên một cấp độ (ra khỏi đối tượng chủ đề):
> 
> ```
> vuetify: {
>   breakpoint: {
>      ...
>   }
> }
> ```

You tested ? im not working

**Comment by kevinmarrec** [comment]
For both versions of Vuetify Nuxt Module (Vuetify 1.5.x / Vuetify 2) :
```
vuetify: {
  breakpoint: {
    thresholds: {
      xs: 340,
      sm: 540,
      md: 800,
      lg: 960,
      xl: 1280,
    }
}
```

Nuxt module is just passing these options to Vuetify initialization, so if there is something still not working, please open an issue on Vuetify itself.
