### ISSUE TITLE
$vuetify is not present in context

### ISSUE THREAD

**Issue by eliyas5044** [nuxt-community/vuetify-module#47]
Thanks for your great work. `$vuetify` is not present in nuxt context. if we try to see in mounted hook, it's working
```
mounted() {
    console.log(this.$vuetify);
}
```
if we want to see in plugin, $vuetify is undefined
```
export default function({$vuetify}) {
  console.log($vuetify);
}
```
or
```
export default function({app}) {
  console.log(app.$vuetify);
}
```
if we check all context, $vuetify is not there
```
export default function(cxt) {
  console.log(cxt);
}
```

**Comment by mgreengithelps** [comment]
Could be wrong, but it should not be available in plugins, per [Nuxt Plugin page](https://nuxtjs.org/guide/plugins):

> Nuxt.js allows you to define JavaScript plugins to be run before instantiating the root Vue.js Application. This is especially helpful when using your own libraries or external modules.

So if the Vue app is not instantiated yet, then I would suspect you would not be able to access $vuetify within any plugins.

**Comment by eliyas5044** [comment]
@mgreengithelps acctullay they forgot to add it in plugin for branch `master`. Please check these two plugin file. [Lastet Plugin](https://github.com/nuxt-community/vuetify-module/blob/next/lib/plugin.js), [Master branch plugin](https://github.com/nuxt-community/vuetify-module/blob/master/lib/plugin.js)

**Comment by gotenxds** [comment]
+1 I struggled with this for 5 hours yesterday, thought I was the bug...

**Comment by eliyas5044** [comment]
@kevinmarrec sorry for late reply. This is necessary in context menu, if we want to localize vuetify. please check my use case. I used `nuxt/i18n` for my localization. Now i want to change `vuetify` local when `i18n` change.
> `plugins/i18n.js`
```
export default function({ app }) {
  // onLanguageSwitched called right after a new locale has been set
  app.i18n.onLanguageSwitched = (oldLocale, newLocale) => {
    app.$vuetify.lang.current = newLocale;
  };
}
```
or
```
export default function({ $vuetify}) {
  // onLanguageSwitched called right after a new locale has been set
  app.i18n.onLanguageSwitched = (oldLocale, newLocale) => {
    $vuetify.lang.current = newLocale;
  };
}
```
Thanks

**Comment by kevinmarrec** [comment]
@eliyas5044 Alright I see, seems common use case, will fix that on both branches and will release new version soon

**Comment by kevinmarrec** [comment]
@eliyas5044 If you're using 1.5, can you try this ?

Create a new plugin that does :
```js
export default (ctx) {
  ctx.$vuetify = Vue.prototype.$vuetify
}
```

> `Vue.prototype.$vuetify` is set by Vuetify installation (`Vue.use(Vuetify)`)

And tell me if it works.

**Comment by eliyas5044** [comment]
@kevinmarrec sorry to comment in closed issue, but still same, please check [plugin](https://github.com/nuxt-community/vuetify-module/blob/0.x/lib/plugin.js) file.

**Comment by tincho425** [comment]
I've tried doing:
`app.vuetify.framework.theme.themes.light.primary = obj`
or
`app.context.$vuetify.theme.themes.light.primary = obj`
in /plugins/combined-inject.js. And calling the injected method in asyncData by
`context.app.$colorsChangeVuetify({"base":"#FFA000","lighten1":"#6A1B9A"})`

But the color is not being updated in the Vuetify theme configuration. What I'm doing wrong? Thanks in advance!
