### ISSUE TITLE
Missing peer dependency 

### ISSUE THREAD

**Issue by douira** [nuxt-community/vuetify-module#49]
When I install the 2 version of this package I get following warning:
```
npm WARN vue-loader@15.7.0 requires a peer of css-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN vuetify-loader@1.2.2 requires a peer of vuetify@^1.3.0 but none is installed. You must install peer dependencies yourself.
```
`vue-loader` is included in `nuxt@2.8.1` and it requires ` css-loader@*` as a peer dependency. Do I need to install it?
`vuetify-loader@1.2.2` is required by `@nuxtjs/vuetify@1.0.0-beta.6` as a dependency. Do I need to install it? Shouldn't `vuetify-loader@1.2.2` have been installed already because it's a direct dependency of `@nuxtjs/vuetify@1.0.0-beta.6`?

**Comment by mgreengithelps** [comment]
You do have vuetify-loader installed, that is where the second warning is coming from. Probably because you are using the vuetify beta release (from @nuxtjs/vuetify@1.0.0-beta.6) and the vuetify-loader is still set to expect a stable release (but is fine to use with beta vuetify) for use in production. You would have to ask the maintainers of the vuetify-loader repository, but I am going to guess that is what is going on there. Either way, I think you can ignore that warning while using the beta release of vuetify-module.

**Comment by douira** [comment]
thanks, ok so that solves the second one. Do you know anything about the first issue? The fact that I can't install a newer version than 1.0.1 of `css-loader` because it's being used wrong by nuxt is pretty annoying.

**Comment by mgreengithelps** [comment]
Hmm yeah not sure, you may want to try asking in [vue-loader](https://github.com/vuejs/vue-loader) or [nuxt](https://github.com/nuxt/nuxt.js)

Did you follow the instructions for installing the vuetify-module, it is using a Nuxt edge package and not a Nuxt stable package, "nuxt-edge": "^2.9.0-26035210.efd242ad", you mentioned you are using nuxt@2.8.1?

Maybe delete your node_modules directory and try reinstalling with Nuxt edge?

**Comment by douira** [comment]
The problem with the peer dependency of `css-loader@*` being ok with all versions has been around for a while. I just updated from my older Vuetify 1.5 installation to this new module. This problem was happening with older (stable) nuxt versions as well. It would be nice if they either set the version to have to be 1.* or just update their use of `css-loader`'s api as it's at version 3 now.

**Comment by mgreengithelps** [comment]
I see, if you have not seen an explanation before then maybe ask in vue-loader and see if they have an explanation as to why it is set up this way? Sorry I couldn't help anymore than that.

**Comment by douira** [comment]
thanks for the help. I'll take the issue with `css-loader` to `vue-loader`'s issues.
