### ISSUE TITLE
Question about A La Carte of Vuetify

### ISSUE THREAD

**Issue by furyscript** [nuxt-community/vuetify-module#5]
Is it possible to import single components of Vuetify with A La Carte?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/modules/issues/c147">#c147</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. You can use `treeShake` option.

**Comment by furyscript** [comment]
Yes I see but when I use this options and import this in my component:
```
<script>
import { VApp, VParallax } from 'vuetify/lib'
export default {
  components: {
    VApp,
    VParallax
  },
}
</script>
```
I see that all stylus is compiled (from view-source of chrome) with components that I don't need like v-chip, v-btn etc.
I installed `stylus` and `stylus-loader` and `vuetify-loader`
This problem is on `vuetify/lib`?

**Comment by furyscript** [comment]
Sorry, i resolve this issue.
It's because in development we have all stylus but in production webpack select only what I used. So the style will come clean.

**Comment by furyscript** [comment]
Is it possible to set clean css in development? Because I have also bootstrap-vue and I need only VParallax of vuetify. If compiler build all stylus of vuetify create conflict with bootstrap vue...

**Comment by xloading** [comment]
Hi @furyscript!
Have you resolved this somehow? Facing the same difficulty at the moment.

**Comment by ricardogobbosouza** [comment]
@furyscript, @xloading 
https://github.com/nuxt-community/vuetify-module/issues/5#issuecomment-461353410

**Comment by ricardogobbosouza** [comment]
@kevinmarrec can closed?
