### ISSUE TITLE
Cannot read properties of undefined (reading 'resolveAlias') with Nuxt3

### ISSUE THREAD

**Issue by parabellumKoval** [nuxt-community/vuetify-module#510]
I try to use vuetify 2 with Nuxt 3
```
"devDependencies": {
    "@nuxtjs/vuetify": "^1.12.3",
    "nuxt": "3.0.0-rc.8"
    ...
}
```
Nuxt config is
```
export default defineNuxtConfig({
    buildModules: [
      '@nuxtjs/vuetify',
    ],
})
```
when i make `npm run dev` i get error 
```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'resolveAlias')                                        20:03:01

  at Object.setupBuild (node_modules/@nuxtjs/vuetify/dist/build.js:24:40)
  at node_modules/@nuxtjs/vuetify/dist/index.js:14:20
  at node_modules/hookable/dist/index.mjs:39:70
  at async build (node_modules/nuxt/dist/index.mjs:1838:3)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6770:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6813:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)


```

is it possible to fix this somehow? Thx

**Comment by somephysicist** [comment]
See also https://github.com/nuxt-community/vuetify-module/issues/513, https://github.com/nuxt-community/vuetify-module/issues/475

Not even bridge is supported, see also: https://github.com/nuxt-community/vuetify-module/issues/471, https://github.com/nuxt-community/vuetify-module/issues/509

In case anyone is still wondering or just for closure: Vuetify 2 isn't compatible with Vue 3, which Nuxt 3 is based on. Another thread linked to https://codybontecou.com/how-to-use-vuetify-with-nuxt-3.html to show you can use a prerelease version of Vuetify 3 with Nuxt 3.

**Comment by harlan-zw** [comment]
Tracking here https://github.com/nuxt-community/vuetify-module/issues/522
