### ISSUE TITLE
I think treeShake not work....

### ISSUE THREAD

**Issue by ksbgenius** [nuxt-community/vuetify-module#64]
in nuxtjs/vuetify 1.0.0

in nuxt.config.js

vuetify: {
    treeShake: true,
    theme: {
      primary: colors.blue.darken2,
      accent: colors.grey.darken3,
      secondary: colors.amber.darken3,
      info: colors.teal.lighten1,
      warning: colors.amber.base,
      error: colors.deepOrange.accent4,
      success: colors.green.accent3
    }
  }

when
yarn build and yarn start

vuetify component showing blink..
I think vuetify-loader not working..
check this..

my package.json is
"private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "yarn lint",
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.5.4",
    "@nuxtjs/pwa": "^3.0.0-beta.16",
    "@nuxtjs/vuetify": "^1.0.0",
    "cross-env": "^5.2.0",
    "nuxt": "^2.8.1"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^0.0.1",
    "@nuxtjs/eslint-module": "^0.0.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.15.1",
    "eslint-config-standard": ">=12.0.0",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "nodemon": "^1.18.9",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  }

**Comment by kevinmarrec** [comment]
@ksbgenius Can you either provide repository or a GIF of the blink ?

**Comment by kevinmarrec** [comment]
@ksbgenius I tried and I've not being able to reproduce your issue.
It also seems you meant
```js
vuetify: {
  treeShake: true,
  themes: {
    light: {
      primary: ...
    }
  }
}
```

instead of 

```
vuetify: {
  treeShake: true,
  theme: {
    primary: ...
  }
}
```

**Comment by kevinmarrec** [comment]
@ksbgenius Furthermore Vuetify 2.0 is using `sass` and not `stylus` anymore.

I don't have any issues with theme options in production (with treeShake on)
So i'm closing this issue. Please open new issue with a proper repository reproduction if you face another issue. You can also visit us on discord -> https://discord.nuxtjs.org
