### ISSUE TITLE
Add a config to make it possible to only add some parts of vuetify to a project

### ISSUE THREAD

**Issue by jhd4tmr** [nuxt-community/vuetify-module#65]

**Comment by kevinmarrec** [comment]
@jhd4tmr Are you looking for `treeShake` option that is automatically set to `true` when having `NODE_ENV === 'production'` ?

I don't what you mean about only adding some parts of vuetify, `treeShake` will only bundle Vuetify components you're using and not the rest.

**Comment by enzonotario** [comment]
Hi @kevinmarrec ! I have some components in `node_modules` and the `treeShake` option doesn't take in count those components, so the loader doesn't include the vuetify part that those components are using.
So, how can I tell the loader that should take in count also some node_modules folder?

Thanks in advance!
