### ISSUE TITLE
Upgrade create-nuxt-app

### ISSUE THREAD

**Issue by stact** [nuxt-community/vuetify-module#66]
Hi
Thx for upgrade to vuetify 2.0!
Does https://nuxtjs.org/guide/installation/ create-nuxt-app will upgrade soon too?

Thx for your feedback!

**Comment by jhd4tmr** [comment]
you can use npm install @nuxt/vuetify@1.0.0 to upgrade the package

**Comment by ricardogobbosouza** [comment]
@jhd4tmr Some changes to use vuetify 2.0
https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0

**Comment by ricardogobbosouza** [comment]
@stact https://github.com/nuxt/create-nuxt-app/pull/297
