### ISSUE TITLE
Sass support in next branch ?

### ISSUE THREAD

**Issue by gotenxds** [nuxt-community/vuetify-module#68]
Hello, I might have missed something but I keep getting errors like this when trying to use sass in next branch: 

![image](https://user-images.githubusercontent.com/3519520/61819451-c3b22600-ae5b-11e9-9f0b-bf47e74cccd1.png)

**Comment by kevinmarrec** [comment]
@gotenxds What do you mean by "using next branch" ? Which version of the module ?
Please provide a repository so I can help debugging

**Comment by ricardogobbosouza** [comment]
@gotenxds see https://nuxtjs.org/faq/pre-processors/
use  `<style lang="sass">` not `<style type="sass">`

**Comment by ricardogobbosouza** [comment]
@kevinmarrec can closed?
