### ISSUE TITLE
Changing theme colors does not work in 'spa' mode

### ISSUE THREAD

**Issue by theomjones** [nuxt-community/vuetify-module#69]
When `mode: 'universal'` is set in nuxt config, this works as expected. When it's `mode: 'spa'`, you cannot change the color dynamically within a component.

A weird thing to note is that you _can change_ it from within a plugin by accessing Context, but not with the object provided on the vue instance. Are they potentially different references?

Please see the codesandbox below to reproduce this. 
https://codesandbox.io/embed/codesandbox-nuxt-grfcx

**Comment by kevinmarrec** [comment]
@theomjones Indeed there isa bug, but I don't have clues for now about what's going on.
I'm investigating and yes I think there are different references.

It's Vuetify that register `$vuetify` on Vue instances, so it may be Vuetify issue.
Gonna keep investigating and see with Vuetify team if can find a solution.

**Comment by kevinmarrec** [comment]
@theomjones Found the issue, in `spa` mode it gets overriden by default theme cause of some behavior that should not do Vuetify when Nuxt is in `spa` mode.

You can check the `<head>` styles tags with `vuetify-theme-stylesheet` ids between `universal` and `spa`

**Comment by kevinmarrec** [comment]
> In Nuxt SPA mode there are unfortunately 2 Vuetify stylesheets in DOM, the first one is the right one and the one to be updated when dynamically change theme in Vue. But the second one is always the same and added by `initNuxt` around Vuetify code. And as it comes in second as style tag in DOM order, it always overrides the right theme above, leading in no visible changes.

**Comment by KaelWD** [comment]
For some reason we aren't using Vue reactivity for the theme, there's a `setTheme` method instead.

**Comment by kevinmarrec** [comment]
`setTheme` may only a workaround for now, we just need to fix Vuetify initialization that is not currently correctly handled for Nuxt projects not using SSR i.e `spa` mode.

@theomjones Just letting you know I'm working on a solution around Vuetify source code, I'll keep this thread updated when solution will be found, when PR will be merged, and when Vuetify will release the fix. (It should lands in Vuetify 2.0.2 or 2.0.3)

**Comment by johnleider** [comment]
@KaelWD https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/theme/index.ts#L216

**Comment by kevinmarrec** [comment]
@KaelWD FYI theme reactivity works in Nuxt SPA, css is just overriden by a duplicate css that never change, more detailed info in my PR fix on Vuetify repo :)

**Comment by kevinmarrec** [comment]
Reopening the issue as the Vuetify change that was making this issue fixed led to more important issues, so the change was reverted in https://github.com/vuetifyjs/vuetify/pull/8234.
