### ISSUE TITLE
[Bug Report] Vuetify custom icon component throws compile error

### ISSUE THREAD

**Issue by bubinek** [nuxt-community/vuetify-module#71]
### Versions

**Nuxt:** 2.8.1
**@nuxtjs/vuetify:** 1.0.0

### Reproduction Link

https://codesandbox.io/s/vuetify-font-awesome-svg-custom-icon-components-bqnce?fontsize=14

### Actual Behavior

[Vuetify custom icon component](https://vuetifyjs.com/en/customization/icons#custom-font-awesome-pro-icons) throws compile error:

```
ERROR  Could not compile template /sandbox/node_modules/@nuxtjs/vuetify/lib/plugin.js: Serializing native function: Boolean
```

Following config contains `component` prop which I assume will not pass through `serializeFunction` in [lib/plugin.js:11](https://github.com/nuxt-community/vuetify-module/blob/master/lib/plugin.js#L11).

```js
icons: {
  values: {
    heart: {
      component: FontAwesomeIcon,
      props: {
        icon: ["fas", "heart"]
      }
    }
  }
}
```

**Comment by kevinmarrec** [comment]
@ricardogobbosouza Maybe you have any ideas ?

**Comment by ricardogobbosouza** [comment]
@bubinek what you are trying to do will not work.
You need to use plugins, see: https://github.com/nuxt-community/vuetify-module/issues/37#issuecomment-514665227

**Comment by kevinmarrec** [comment]
@bubinek 

@ricardogobbosouza is right, Nuxt can serialize function but can't serialize components.
Maybe `component: () => import('path/to/your/custom/component')` could work without needing plugin ?

**Comment by kevinmarrec** [comment]
@bubinek 

Closing in favor of #77 which will implements more suitable solution to your needs.
In the meanwhile, you can use custom plugin as @ricardogobbosouza suggested.
