### ISSUE TITLE
request README.md update

### ISSUE THREAD

**Issue by ksbgenius** [nuxt-community/vuetify-module#72]
vuetify 2.0.0 release

and i think

request update README.md

**Comment by kevinmarrec** [comment]
@ksbgenius What is the request ? I'm not sure to understand.
You request a new section in README.md ?

**Comment by ricardogobbosouza** [comment]
maybe a section on how to migrate to v2 is interesting

**Comment by kevinmarrec** [comment]
@ricardogobbosouza Yeah, it at least needs link to Vuetify 2 upgrade guide.
We indeed need guidelines from 0.5.x to 1.x of the Vuetify module (mostly removing dependencies as they are shipped now, update options passed to the module)
