### ISSUE TITLE
[Vuetify 2.0] Icon not showing

### ISSUE THREAD

**Issue by rosnaib11** [nuxt-community/vuetify-module#76]
I just upgrade to vuetify 2.0.1 and v-icon seems not working same what happened in #38

**Comment by kevinmarrec** [comment]
@rosnaib11 Please provide repository with repdrouction, I can't help just with this description.

Please be aware that Vuetify 2 use MDI icons by default now and they need `mdi-` prefixes.

**Comment by rosnaib11** [comment]
My bad, its now having `mdi-` prefix to call thanks.
