### ISSUE TITLE
Use a file for vuetifyOptions over raw module options

### ISSUE THREAD

**Issue by kevinmarrec** [nuxt-community/vuetify-module#77]
After reading https://github.com/nuxt-community/vuetify-module/issues/27#issuecomment-514535526, an idea came to my mind : 

**Implementing a way to provide a path to a file that contains the vuetifyOptions**

-> Make it watched by Nuxt and means being able to update icons, theme, etc... **without having to wait for full Nuxt rebuild**. 

-> As it would be imported in https://github.com/nuxt-community/vuetify-module/blob/master/lib/plugin.js , it's a plugin which means you could even **write the options in TypeScript without needing TypeScript runtime**, just TypeScript build, which means less dependencies to install (unless you're already using TypeScript runtime for other pieces of your configuration file)

-> Globally it should fix any issue that was caused by serialization of the module options which means : `theme.options.minifyTheme` function, `theme.options.themeCache` using cache like **LRU**, `theme.icons.values.xxx.component` custom icon component.

Related :
https://github.com/nuxt-community/vuetify-module/issues/27
https://github.com/nuxt-community/vuetify-module/issues/71

**Comment by BotellaA** [comment]
I tried [#37](https://github.com/nuxt-community/vuetify-module/issues/37#issuecomment-514665227) as proposed solution in #71 but it does not work.

Here is an example: https://codesandbox.io/embed/vuetify-custom-icon-components-zqzi8
