### ISSUE TITLE
Generated "vendors.app" Chunk Large

### ISSUE THREAD

**Issue by propsoft** [nuxt-community/vuetify-module#79]
With Vuetify version 1.5 the generated vendor.app JS file size for our app is 232KiB.  When upgrading to Vuetify 2.0 with this module, the build size is double, 464 KiB.

With a fresh Nuxt and @nuxtjs/vuetify-module install the build size is still 362KiB.  

After doing a Lighthouse audit, it is showing that: "[id] attributes on the page are not unique... The value of an id attribute must be unique to prevent other instances from being overlooked by assistive technologies."  and the Failing Elements are: (3) "style#vuetify-theme-stylesheet"

Here are some screenshots of the build log. Can anyone else reproduce this?

**Vuetify 1.5 (full app)**
<img width="1070" alt="full-app-1 5-version" src="https://user-images.githubusercontent.com/21713053/61983699-4818bc00-afb6-11e9-8288-d692e9e239a7.png">

**Vuetify 2.0 (full app)**
<img width="1070" alt="full-app-2 0-version" src="https://user-images.githubusercontent.com/21713053/61983697-46e78f00-afb6-11e9-887d-e31fd571791b.png">

**Vuetify 2.0 (fresh install)**
<img width="1070" alt="clean-install" src="https://user-images.githubusercontent.com/21713053/61983698-46e78f00-afb6-11e9-8d61-8e9a0ee7f2c3.png">

**Comment by kevinmarrec** [comment]
@propsoft First of all, Vuetify 2.0 has non-neglibable bigger full bundle than Vuetify 1.5 cause it contains new stuff (mostly new components)

About the fresh install size, you're right but if you look into the concerned file, you'll notice there's lot of css. Lof of these css won't be used, so you would need to use Nuxt `extractCSS` so it extracts CSS, and try to use https://github.com/Developmint/nuxt-purgecss to purge unused CSS.

**Comment by kevinmarrec** [comment]
I just tried https://nuxtjs.org/api/configuration-build/#extractcss on a project, it seems to fix the JS high bundle size.

**Comment by propsoft** [comment]
Makes sense and thank you for the help @kevinmarrec 😄
