### ISSUE TITLE
devModules

### ISSUE THREAD

**Issue by jesse996** [nuxt-community/vuetify-module#87]
int the READEME,
shouldn't it be 'modules'?
i can't find the `devModule` option in the NUXT document,only `modules`,
and i set in the `modules` it works

**Comment by pi0** [comment]
It is to reduce production install size (adding module to devDependencies) and faster startup time. Vuetify module is used only during build.

I'll add a PR for docs

**Comment by jesse996** [comment]
ok ,tks~

**Comment by jesse996** [comment]
> It is to reduce production install size (adding module to devDependencies) and faster startup time. Vuetify module is used only during build.
> 
> I'll add a PR for docs

but it doesn't work well when i put it in the `devModules`

**Comment by jesse996** [comment]
sorry i made a stupid mistake,it works well ,and thank you very much!
