### ISSUE TITLE
How to upgrade to latest version of vuetify?

### ISSUE THREAD

**Issue by marcusaaronb** [nuxt-community/vuetify-module#92]
**Module version**
The version of the module you're using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ianfortier** [comment]
When they said "use this template" they mean fill it with your problem LOL

**Comment by kevinmarrec** [comment]
Hey @marcusaaronb, :) you Indeed didn't fill the template. About upgrading to last version of Vuetify, 2 cases :

1) You are using 1.5.x : https://github.com/nuxt-community/vuetify-module/blob/master/MIGRATION_GUIDE.md

2) You're already using 2.0 : just upgrade to the last version of this Nuxt module.
