### ISSUE TITLE
Minimal configuration not applying roboto

### ISSUE THREAD

**Issue by stact** [nuxt-community/vuetify-module#93]
**Module version**
1.1.0

**Describe the bug**
It seems that Roboto is not applying.

**To Reproduce**
https://codesandbox.io/s/codesandbox-nuxt-yt253
https://yt253.sse.codesandbox.io/

1. Install nuxt
2. Add dev dependency @nuxtjs/vuetify
3. Customize the layout to integrate a vuetify component with text (card for example)
3. Launch yarn dev or yarn start
4. See the home page and check the text style (no roboto applied)
5. Network loads google font

**Expected behavior**
Roboto must apply without

**Comment by kevinmarrec** [comment]
Hi @stact , your entire application should be wrapped in a `v-app`.
https://vuetifyjs.com/en/getting-started/frequently-asked-questions#my-application-does-not-look-correct

It means you need to wrap your layout in a `v-app` tag, see the fix here :

https://codesandbox.io/s/codesandbox-nuxt-9g28d
https://9g28d.sse.codesandbox.io/
