### ISSUE TITLE
Not work in Edge, error:'SCRIPT1028'

### ISSUE THREAD

**Issue by ba-kuwajima** [nuxt-community/vuetify-module#95]
**@nuxtjs/vuetify version**: 1.1.1

https://github.com/vuetifyjs/vuetify/issues/8279

It is the same situation.

I tried
```
// nuxt.config.js

  build: {
    parallel: true,
    transpile: [/vuetify/],
    babel: {
      presets: [
        [
          '@babel/preset-env',
          {
            useBuiltIns: 'usage',
            corejs: 3
          }
        ]
      ]
    }
  }
```

```
// Edge console
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
```

How can i fix it?

**Comment by kevinmarrec** [comment]
@ba-kuwajima

https://github.com/nuxt-community/vuetify-module/blob/ed14664cc9dc8204bdfd1374c114fe5c759e22b6/lib/module.js#L91

It's only available when using treeShake option, are you using it ?

**Comment by ba-kuwajima** [comment]
Thanks for the feedback.

I tried
```
// nuxt.config.js

vuetify: {
   // ...
    treeShake: true
},
build: {
    parallel: true,
    babel: {
      presets: [
        [
          '@babel/preset-env',
          {
            useBuiltIns: 'usage',
            corejs: 3
          }
        ]
      ]
    },
   //...
}
```
But I still get an error


Change node_modules/@nuxtjs/vuetify/lib/module.js  from /^vuetify/ to /vuetify/

```
// module.js
this.options.build.transpile.push(/vuetify/)
```

It's working as expected.

**Comment by kevinmarrec** [comment]
@ba-kuwajima So you can confirm that removing the `^` from the transpile regex fixes the issue on Edge ? I can't really test as I'm on Linux.
